In [1]:
import pandas as pd
import numpy as np

In [2]:
college = pd.read_csv('data/college.csv',index_col = 'INSTNM')
college.head(10)

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5
The University of Alabama,Tuscaloosa,AL,0.0,0.0,0.0,0,555.0,565.0,0.0,29851.0,...,0.0261,0.0268,0.0026,0.0844,1,0.2040,0.4010,0.0853,41900,23750
Central Alabama Community College,Alexander City,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,1592.0,...,0.0000,0.0000,0.0019,0.3882,1,0.5892,0.3977,0.3153,27500,16127
Athens State University,Athens,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,2991.0,...,0.0174,0.0057,0.0334,0.5517,1,0.4088,0.6296,0.6410,39000,18595
Auburn University at Montgomery,Montgomery,AL,0.0,0.0,0.0,0,486.0,509.0,0.0,4304.0,...,0.0297,0.0397,0.0246,0.2853,1,0.4192,0.5803,0.2930,35000,21335
Auburn University,Auburn,AL,0.0,0.0,0.0,0,575.0,588.0,0.0,20514.0,...,0.0000,0.0100,0.0140,0.0862,1,0.1610,0.3494,0.0415,45700,21831

In [3]:
city = college['CITY']
city.head()

INSTNM
Alabama A & M University                   Normal
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
University of Alabama in Huntsville    Huntsville
Alabama State University               Montgomery
Name: CITY, dtype: object

The .iloc indexer makes selections only by integer location. Passing an integer to it returns a Scalar value.

In [4]:
city.iloc[3]

'Huntsville'

To select several different integer locations, pass a list to .iloc. This returns a series.

In [5]:
city.iloc[[10,20,30]]

INSTNM
Birmingham Southern College                            Birmingham
George C Wallace State Community College-Hanceville    Hanceville
Judson College                                             Marion
Name: CITY, dtype: object

In [6]:
city.iloc[4:50:10]

INSTNM
Alabama State University              Montgomery
Enterprise State Community College    Enterprise
Heritage Christian University           Florence
Marion Military Institute                 Marion
Reid State Technical College           Evergreen
Name: CITY, dtype: object

The .loc indexer makes selections only index labels. Passing a single string returns a Scalar value.

In [7]:
city.loc['Heritage Christian University']

'Florence'

In [8]:
city.loc['Alabama State University':'Reid State Technical College':10]

INSTNM
Alabama State University              Montgomery
Enterprise State Community College    Enterprise
Heritage Christian University           Florence
Marion Military Institute                 Marion
Reid State Technical College           Evergreen
Name: CITY, dtype: object

In [9]:
city.iloc[[3]]

INSTNM
University of Alabama in Huntsville    Huntsville
Name: CITY, dtype: object

In [10]:
city.loc['Reid State Technical College':'Alabama State University':10]

Series([], Name: CITY, dtype: object)

In [11]:
 college.iloc[60]

CITY                  Anchorage
STABBR                       AK
HBCU                          0
MENONLY                       0
WOMENONLY                     0
RELAFFIL                      0
SATVRMID                    NaN
SATMTMID                    NaN
DISTANCEONLY                  0
UGDS                      12865
UGDS_WHITE               0.5747
UGDS_BLACK               0.0358
UGDS_HISP                0.0761
UGDS_ASIAN               0.0778
UGDS_AIAN                0.0653
UGDS_NHPI                0.0086
UGDS_2MOR                 0.098
UGDS_NRA                 0.0181
UGDS_UNKN                0.0457
PPTUG_EF                 0.4539
CURROPER                      1
PCTPELL                  0.2385
PCTFLOAN                 0.2647
UG25ABV                  0.4386
MD_EARN_WNE_P10           42500
GRAD_DEBT_MDN_SUPP      19449.5
Name: University of Alaska Anchorage, dtype: object

In [12]:
college.loc['University of Alaska Anchorage']

CITY                  Anchorage
STABBR                       AK
HBCU                          0
MENONLY                       0
WOMENONLY                     0
RELAFFIL                      0
SATVRMID                    NaN
SATMTMID                    NaN
DISTANCEONLY                  0
UGDS                      12865
UGDS_WHITE               0.5747
UGDS_BLACK               0.0358
UGDS_HISP                0.0761
UGDS_ASIAN               0.0778
UGDS_AIAN                0.0653
UGDS_NHPI                0.0086
UGDS_2MOR                 0.098
UGDS_NRA                 0.0181
UGDS_UNKN                0.0457
PPTUG_EF                 0.4539
CURROPER                      1
PCTPELL                  0.2385
PCTFLOAN                 0.2647
UG25ABV                  0.4386
MD_EARN_WNE_P10           42500
GRAD_DEBT_MDN_SUPP      19449.5
Name: University of Alaska Anchorage, dtype: object

In [13]:
college.iloc[[60,99,3]]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
University of Alaska Anchorage,Anchorage,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,12865.0,...,0.0980,0.0181,0.0457,0.4539,1,0.2385,0.2647,0.4386,42500,19449.5
International Academy of Hair Design,Tempe,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,188.0,...,0.0160,0.0000,0.0638,0.0000,0,0.7185,0.7346,0.3905,22200,10556
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097

In [14]:
labels = ['University of Alaska Anchorage','International Academy of Hair Design','University of Alabama in Huntsville']
college.loc[labels]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
University of Alaska Anchorage,Anchorage,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,12865.0,...,0.0980,0.0181,0.0457,0.4539,1,0.2385,0.2647,0.4386,42500,19449.5
International Academy of Hair Design,Tempe,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,188.0,...,0.0160,0.0000,0.0638,0.0000,0,0.7185,0.7346,0.3905,22200,10556
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097

In [15]:
college.iloc[99:102]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
International Academy of Hair Design,Tempe,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,188.0,...,0.0160,0.0000,0.0638,0.0000,0,0.7185,0.7346,0.3905,22200,10556
GateWay Community College,Phoenix,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,5211.0,...,0.0127,0.0161,0.0702,0.7465,1,0.3270,0.2189,0.5832,29800,7283
Mesa Community College,Mesa,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,19055.0,...,0.0205,0.0257,0.0682,0.6457,1,0.3423,0.2207,0.4010,35200,8000

In [16]:
start = 'International Academy of Hair Design'
stop = 'Mesa Community College'
college.loc[start:stop]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
International Academy of Hair Design,Tempe,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,188.0,...,0.0160,0.0000,0.0638,0.0000,0,0.7185,0.7346,0.3905,22200,10556
GateWay Community College,Phoenix,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,5211.0,...,0.0127,0.0161,0.0702,0.7465,1,0.3270,0.2189,0.5832,29800,7283
Mesa Community College,Mesa,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,19055.0,...,0.0205,0.0257,0.0682,0.6457,1,0.3423,0.2207,0.4010,35200,8000

In [17]:
college.iloc[:3,:4]

                                           CITY STABBR  HBCU  MENONLY
INSTNM
Alabama A & M University                 Normal     AL   1.0      0.0
University of Alabama at Birmingham  Birmingham     AL   0.0      0.0
Amridge University                   Montgomery     AL   0.0      0.0

In [18]:
college.iloc[:,[4,6]].head()

                                     WOMENONLY  SATVRMID
INSTNM
Alabama A & M University                   0.0     424.0
University of Alabama at Birmingham        0.0     570.0
Amridge University                         0.0       NaN
University of Alabama in Huntsville        0.0     595.0
Alabama State University                   0.0     425.0

In [19]:
college.loc[:,['WOMENOLY','SATVRMID']].head()

C:\Users\kbhar\Anaconda3\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

                                     WOMENOLY  SATVRMID
INSTNM
Alabama A & M University                  NaN     424.0
University of Alabama at Birmingham       NaN     570.0
Amridge University                        NaN       NaN
University of Alabama in Huntsville       NaN     595.0
Alabama State University                  NaN     425.0

In [20]:
college.iloc[[100,200],[7,15]]

                                       SATMTMID  UGDS_NHPI
INSTNM
GateWay Community College                   NaN     0.0029
American Baptist Seminary of the West       NaN        NaN

In [21]:
rows = ['GateWay Community College','American Bapist Seminary of the West']
columns = ['SATMTMID','UGDS_NHPI']
college.loc[rows,columns]

                                      SATMTMID  UGDS_NHPI
INSTNM
GateWay Community College                  NaN     0.0029
American Bapist Seminary of the West       NaN        NaN

In [22]:
college.iloc[5,-4]

0.401

In [23]:
college.loc['The University of Alabama','PCTFLOAN']

0.401

In [24]:
college.iloc[90:80:-2,5]

INSTNM
Empire Beauty School-Flagstaff     0
Charles of Italy Beauty College    0
Central Arizona College            0
University of Arizona              0
Arizona State University-Tempe     0
Name: RELAFFIL, dtype: int64

In [25]:
college.iloc[:10]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5
The University of Alabama,Tuscaloosa,AL,0.0,0.0,0.0,0,555.0,565.0,0.0,29851.0,...,0.0261,0.0268,0.0026,0.0844,1,0.2040,0.4010,0.0853,41900,23750
Central Alabama Community College,Alexander City,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,1592.0,...,0.0000,0.0000,0.0019,0.3882,1,0.5892,0.3977,0.3153,27500,16127
Athens State University,Athens,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,2991.0,...,0.0174,0.0057,0.0334,0.5517,1,0.4088,0.6296,0.6410,39000,18595
Auburn University at Montgomery,Montgomery,AL,0.0,0.0,0.0,0,486.0,509.0,0.0,4304.0,...,0.0297,0.0397,0.0246,0.2853,1,0.4192,0.5803,0.2930,35000,21335
Auburn University,Auburn,AL,0.0,0.0,0.0,0,575.0,588.0,0.0,20514.0,...,0.0000,0.0100,0.0140,0.0862,1,0.1610,0.3494,0.0415,45700,21831

In [26]:
college.iloc[:10, :]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5
The University of Alabama,Tuscaloosa,AL,0.0,0.0,0.0,0,555.0,565.0,0.0,29851.0,...,0.0261,0.0268,0.0026,0.0844,1,0.2040,0.4010,0.0853,41900,23750
Central Alabama Community College,Alexander City,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,1592.0,...,0.0000,0.0000,0.0019,0.3882,1,0.5892,0.3977,0.3153,27500,16127
Athens State University,Athens,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,2991.0,...,0.0174,0.0057,0.0334,0.5517,1,0.4088,0.6296,0.6410,39000,18595
Auburn University at Montgomery,Montgomery,AL,0.0,0.0,0.0,0,486.0,509.0,0.0,4304.0,...,0.0297,0.0397,0.0246,0.2853,1,0.4192,0.5803,0.2930,35000,21335
Auburn University,Auburn,AL,0.0,0.0,0.0,0,575.0,588.0,0.0,20514.0,...,0.0000,0.0100,0.0140,0.0862,1,0.1610,0.3494,0.0415,45700,21831

In [27]:
col_start = college.columns.get_loc('UGDS_WHITE')
col_end = college.columns.get_loc('UGDS_UNKN')+1

In [28]:
college.iloc[:5,col_start:col_end]

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [29]:
row_start = college.index[10]
row_end = college.index[15]
college.loc[row_start:row_end,'UGDS_WHITE':'UGDS_UNKN']

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Birmingham Southern College,0.7983,0.1102,0.0195,0.0517,0.0102,0.0000,0.0051,0.0000,0.0051
Chattahoochee Valley Community College,0.4661,0.4372,0.0492,0.0127,0.0023,0.0035,0.0151,0.0000,0.0139
Concordia College Alabama,0.0280,0.8758,0.0373,0.0093,0.0000,0.0000,0.0031,0.0466,0.0000
South University-Montgomery,0.3046,0.6054,0.0153,0.0153,0.0153,0.0096,0.0000,0.0019,0.0326
Enterprise State Community College,0.6408,0.2435,0.0509,0.0202,0.0081,0.0029,0.0254,0.0012,0.0069
James H Faulkner State Community College,0.6979,0.2259,0.0320,0.0084,0.0177,0.0014,0.0152,0.0007,0.0009

In [30]:
college.ix[10:16,'UGDS_WHITE':'UGDS_UNKN']

C:\Users\kbhar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Birmingham Southern College,0.7983,0.1102,0.0195,0.0517,0.0102,0.0000,0.0051,0.0000,0.0051
Chattahoochee Valley Community College,0.4661,0.4372,0.0492,0.0127,0.0023,0.0035,0.0151,0.0000,0.0139
Concordia College Alabama,0.0280,0.8758,0.0373,0.0093,0.0000,0.0000,0.0031,0.0466,0.0000
South University-Montgomery,0.3046,0.6054,0.0153,0.0153,0.0153,0.0096,0.0000,0.0019,0.0326
Enterprise State Community College,0.6408,0.2435,0.0509,0.0202,0.0081,0.0029,0.0254,0.0012,0.0069
James H Faulkner State Community College,0.6979,0.2259,0.0320,0.0084,0.0177,0.0014,0.0152,0.0007,0.0009

In [31]:
college[10:20:2]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Birmingham Southern College,Birmingham,AL,0.0,0.0,0.0,1,560.0,560.0,0.0,1180.0,...,0.0051,0.0000,0.0051,0.0017,1,0.1920,0.4809,0.0152,44200,27000
Concordia College Alabama,Selma,AL,1.0,0.0,0.0,1,420.0,400.0,0.0,322.0,...,0.0031,0.0466,0.0000,0.1056,1,0.8667,0.9333,0.2367,19900,PrivacySuppressed
Enterprise State Community College,Enterprise,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,1729.0,...,0.0254,0.0012,0.0069,0.3823,1,0.4895,0.2263,0.3399,24600,8273
Faulkner University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,0.0,2367.0,...,0.0173,0.0182,0.0258,0.2302,1,0.5812,0.7253,0.4589,37200,22000
New Beginning College of Cosmetology,Albertville,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,115.0,...,0.0000,0.0000,0.0000,0.0783,1,0.8224,0.8553,0.3933,NaN,5500

In [32]:
city = college['CITY']
city[10:20:2]

INSTNM
Birmingham Southern College              Birmingham
Concordia College Alabama                     Selma
Enterprise State Community College       Enterprise
Faulkner University                      Montgomery
New Beginning College of Cosmetology    Albertville
Name: CITY, dtype: object

In [33]:
start = 'Mesa Community College'
stop = 'Spokane Community College'
college[start:stop:1500]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Mesa Community College,Mesa,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,19055.0,...,0.0205,0.0257,0.0682,0.6457,1,0.3423,0.2207,0.4010,35200,8000
Hair Academy Inc-New Carrollton,New Carrollton,MD,0.0,0.0,0.0,0,NaN,NaN,0.0,504.0,...,0.0000,0.0000,0.0000,0.4683,1,0.9756,1.0000,0.5882,15200,9666
National College of Natural Medicine,Portland,OR,0.0,0.0,0.0,0,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed

In [34]:
city[start:stop:1500]

INSTNM
Mesa Community College                            Mesa
Hair Academy Inc-New Carrollton         New Carrollton
National College of Natural Medicine          Portland
Name: CITY, dtype: object

In [35]:
college = college.sort_index()
college

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
A & W Healthcare Educators,New Orleans,LA,0.0,0.0,0.0,0,NaN,NaN,0.0,40.0,...,0.0000,0.0000,0.0000,0.1250,1,0.7018,0.8596,0.6667,NaN,19022.5
A T Still University of Health Sciences,Kirksville,MO,0.0,0.0,0.0,0,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,219800,PrivacySuppressed
ABC Beauty Academy,Garland,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,30.0,...,0.0000,0.0000,0.0000,0.0000,0,0.7857,0.0000,0.8286,NaN,PrivacySuppressed
ABC Beauty College Inc,Arkadelphia,AR,0.0,0.0,0.0,0,NaN,NaN,0.0,38.0,...,0.0000,0.0000,0.0000,0.2105,1,0.9815,1.0000,0.4688,PrivacySuppressed,16500
AI Miami International University of Art and Design,Miami,FL,0.0,0.0,0.0,0,NaN,NaN,0.0,2778.0,...,0.0018,0.0025,0.4644,0.2185,1,0.5507,0.6966,0.3262,29900,31000
AIB College of Business,Des Moines,IA,0.0,0.0,0.0,0,NaN,NaN,0.0,1012.0,...,0.0128,0.0198,0.4140,0.2490,1,0.4132,0.7125,0.3209,37000,19732.5
AOMA Graduate School of Integrative Medicine,Austin,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed
ASA College,Brooklyn,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,4551.0,...,0.0132,0.1525,0.0029,0.0650,1,0.7992,0.6527,0.4816,24100,13747
ASI Career Institute,Turnersville,NJ,0.0,0.0,0.0,0,NaN,NaN,0.0,109.0,...,0.0000,0.0000,0.0000,0.0000,1,0.2571,0.2571,0.1818,NaN,PrivacySuppressed
ASM Beauty World Academy,Davie,FL,0.0,0.0,0.0,0,NaN,NaN,0.0,328.0,...,0.0335,0.0000,0.0000,0.9573,1,0.6049,0.6170,0.7344,PrivacySuppressed,3640
ATA Career Education,Spring Hill,FL,0.0,0.0,0.0,0,NaN,NaN,0.0,206.0,...,0.0097,0.0000,0.1650,0.0000,1,0.9167,0.9825,0.5614,PrivacySuppressed,19000
ATA College,Louisville,KY,0.0,0.0,0.0,0,NaN,NaN,0.0,439.0,...,0.0228,0.0000,0.1731,0.0000,1,0.8407,0.9461,0.5644,PrivacySuppressed,19000
ATEP at IVC,Tustin,CA,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,34200,6500
ATI College-Norwalk,Norwalk,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,109.0,...,0.0000,0.0000,0.0000,0.2661,1,0.8549,0.6788,0.4833,PrivacySuppressed,18612.5
ATS Institute of Technology,Highland Heights,OH,0.0,0.0,0.0,0,NaN,NaN,0.0,459.0,...,0.0022,0.0000,0.0044,0.4357,1,0.9881,0.9921,0.8313,22100,19000
AVTEC-Alaska's Institute of Technology,Seward,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,889.0,...,0.0529,0.0000,0.1395,0.6817,1,0.0737,0.0664,0.7127,33500,PrivacySuppressed
Aaniiih Nakoda College,Harlem,MT,0.0,0.0,0.0,0,NaN,NaN,0.0,124.0,...,0.0000,0.0000,0.0000,0.1452,1,0.8433,0.0000,0.4604,20900,PrivacySuppressed
Aaron's Academy of Beauty,Waldorf,MD,0.0,0.0,0.0,0,NaN,NaN,0.0,28.0,...,0.0000,0.0000,0.0000,0.1786,1,0.7222,0.6481,0.4359,PrivacySuppressed,PrivacySuppressed
Abcott Institute,Southfield,MI,0.0,0.0,0.0,0,NaN,NaN,0.0,136.0,...,0.0000,0.0000,0.0074,0.0882,1,0.9190,0.8810,0.4702,NaN,4817
Abdill Career College Inc,Medford,OR,0.0,0.0,0.0,0,NaN,NaN,0.0,41.0,...,0.0000,0.0000,0.0000,0.0000,1,0.6486,0.5878,0.4500,PrivacySuppressed,9500
Abilene Christian University,Abilene,TX,0.0,0.0,0.0,1,530.0,545.0,0.0,3572.0,...,0.0454,0.0423,0.0045,0.0468,1,0.2595,0.5527,0.0381,40200,25985
Abington Memorial Hospital Dixon School of Nursing,Willow Grove,PA,0.0,0.0,0.0,0,NaN,NaN,0.0,224.0,...,0.0268,0.0000,0.0000,0.0000,1,0.4286,0.8527,0.6696,63300,15836
Abraham Baldwin Agricultural College,Tifton,GA,0.0,0.0,0.0,0,465.0,460.0,0.0,3244.0,...,0.0092,0.0151,0.0003,0.2441,1,0.4629,0.4493,0.1523,32000,15085.5
Academia Serrant Inc,Ponce,PR,0.0,0.0,0.0,0,NaN,NaN,0.0,355.0,...,0.0000,0.0000,0.0000,0.0000,1,0.9319,0.0000,0.3949,13600,PrivacySuppressed
Academy College,Bloomington,MN,0.0,0.0,0.0,0,NaN,NaN,0.0,119.0,...,0.0084,0.0000,0.0840,0.4034,1,0.5369,0.6913,0.6779,38500,29069
Academy Di Capelli-School of Cosmetology,Wallingford,CT,0.0,0.0,0.0,0,NaN,NaN,0.0,27.0,...,0.0000,0.0000,0.0000,0.5185,1,0.6471,0.8118,0.1379,PrivacySuppressed,13652.5
Academy di Firenze,Jerome,ID,0.0,0.0,0.0,0,NaN,NaN,0.0,12.0,...,0.0000,0.0000,0.0000,0.0000,1,0.5556,0.4074,0.5500,NaN,PrivacySuppressed
Academy for Careers and Technology,Mullins,SC,0.0,0.0,0.0,0,NaN,NaN,0.0,39.0,...,0.0000,0.0000,0.0000,0.0000,1,0.7400,0.0000,0.8600,NaN,PrivacySuppressed
Academy for Five Element Acupuncture,Gainesville,FL,0.0,0.0,0.0,0,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed
Academy for Jewish Religion-California,Los Angeles,CA,0.0,0.0,0.0,1,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yeshiva Toras Chaim,Lakewood,NJ,0.0,0.0,0.0,0,NaN,NaN,0.0,215.0,...,0.0000,0.0419,0.0000,0.0000,1,0.5989,0.0000,0.0000,NaN,PrivacySuppressed
Yeshiva University,New York,NY,0.0,0.0,0.0,0,620.0,620.0,0.0,2814.0,...,0.0018,0.0490,0.0103,0.0320,1,0.1879,0.2554,0.0094,56000,19000
Yeshiva Yesodei Hatorah,Lakewood,NJ,0.0,0.0,0.0,0,NaN,NaN,0.0,69.0,...,0.0000,0.0145,0.0000,0.0000,1,0.2500,0.0000,0.0000,NaN,PrivacySuppressed
Yeshiva and Kollel Harbotzas Torah,Brooklyn,NY,0.0,1.0,0.0,0,NaN,NaN,0.0,31.0,...,0.0000,0.0000,0.0000,0.0000,1,0.8333,0.0000,0.4800,PrivacySuppressed,PrivacySuppressed
Yeshiva of Far Rockaway Derech Ayson Rabbinical Seminary,Far Rockaway,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,38.0,...,0.0000,0.0000,0.0000,0.0000,1,0.1053,0.0000,NaN,NaN,PrivacySuppressed
Yeshiva of Machzikai Hadas,Brooklyn,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,373.0,...,0.0000,0.0000,0.0000,0.0000,1,0.7867,0.0000,0.0115,PrivacySuppressed,PrivacySuppressed
Yeshiva of Nitra Rabbinical College,Mount Kisco,NY,0.0,1.0,0.0,0,NaN,NaN,0.0,243.0,...,0.0000,0.0000,0.0000,0.0000,1,0.7727,0.0000,0.0045,13200,PrivacySuppressed
Yeshiva of the Telshe Alumni,Riverdale,NY,0.0,1.0,0.0,0,NaN,NaN,0.0,116.0,...,0.0000,0.0172,0.0000,0.0000,1,0.3968,0.0000,0.0000,PrivacySuppressed,PrivacySuppressed
Yeshivah Gedolah Rabbinical College,Miami Beach,FL,0.0,1.0,0.0,1,NaN,NaN,0.0,52.0,...,0.0000,0.0000,0.0000,0.0000,1,0.4902,0.0000,0.0392,PrivacySuppressed,PrivacySuppressed
Yeshivas Be'er Yitzchok,Elizabeth,NJ,0.0,0.0,0.0,0,NaN,NaN,0.0,49.0,...,0.0000,0.0204,0.0000,0.0000,1,0.6066,0.0000,0.4262,PrivacySuppressed,PrivacySuppressed
Yeshivas Novominsk,Brooklyn,NY,0.0,1.0,0.0,0,NaN,NaN,0.0,129.0,...,0.0000,0.0000,0.0000,0.0000,1,0.2797,0.0000,0.0000,PrivacySuppressed,PrivacySuppressed
Yeshivat Mikdash Melech,Brooklyn,NY,0.0,1.0,0.0,0,NaN,NaN,0.0,131.0,...,0.0000,0.0000,0.0000,0.0000,1,0.1118,0.0000,0.0197,PrivacySuppressed,PrivacySuppressed
Yeshivath Beth Moshe,Scranton,PA,0.0,1.0,0.0,1,NaN,NaN,0.0,55.0,...,0.0000,0.0000,0.0000,0.0000,1,0.4615,0.4038,0.0000,PrivacySuppressed,PrivacySuppressed
Yeshivath Viznitz,Monsey,NY,0.0,1.0,0.0,0,NaN,NaN,0.0,498.0,...,0.0000,0.0281,0.0000,0.0000,1,0.8686,0.0000,0.0021,12900,PrivacySuppressed
Yeshivath Zichron Moshe,South Fallsburgh,NY,0.0,1.0,0.0,0,NaN,NaN,0.0,163.0,...,0.0000,0.0675,0.0000,0.0000,1,0.6768,0.0000,0.0000,PrivacySuppressed,PrivacySuppressed
Yo San University of Traditional Chinese Medicine,Los Angeles,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed
York College,York,NE,0.0,0.0,0.0,1,NaN,450.0,0.0,402.0,...,0.0000,0.0000,0.0025,0.0622,1,0.5447,0.7821,0.0980,36600,26540
York College Pennsylvania,York,PA,0.0,0.0,0.0,0,520.0,530.0,0.0,4720.0,...,0.0299,0.0028,0.0133,0.0816,1,0.2520,0.6765,0.0902,47500,26247
York County Community College,Wells,ME,0.0,0.0,0.0,0,NaN,NaN,0.0,1400.0,...,0.0257,0.0043,0.0300,0.6243,1,0.4593,0.2950,0.4075,29300,7262
York County School of Technology-Adult & Continuing Education,York,PA,0.0,0.0,0.0,0,NaN,NaN,0.0,236.0,...,0.0169,0.0000,0.0000,0.6525,1,0.0942,0.1122,0.6724,38800,7695
York Technical College,Rock Hill,SC,0.0,0.0,0.0,0,NaN,NaN,0.0,4747.0,...,0.1007,0.0002,0.0091,0.4803,1,0.5811,0.2219,0.4024,25300,9750
Yorktowne Business Institute,York,PA,0.0,0.0,0.0,1,NaN,NaN,0.0,105.0,...,0.0000,0.0000,0.0000,0.0667,0,0.7881,0.8136,0.5656,24800,20000
Young Harris College,Young Harris,GA,0.0,0.0,0.0,1,500.0,490.0,0.0,1180.0,...,0.0178,0.0729,0.0271,0.0110,1,0.4011,0.6338,0.0260,36600,26000
Youngstown State University,Youngstown,OH,0.0,0.0,0.0,0,475.0,485.0,0.0,10695.0,...,0.0219,0.0103,0.0363,0.1872,1,0.4903,0.6583,0.2492,33600,27000
Yuba College,Marysville,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,6062.0,...,0.0610,0.0003,0.0370,0.5523,1,0.4246,0.0000,0.3883,26900,6000
Yukon Beauty College Inc,Yukon,OK,0.0,0.0,0.0,0,NaN,NaN,0.0,25.0,...,0.0000,0.0000,0.0000,0.0000,1,0.9259,0.8148,0.4706,PrivacySuppressed,PrivacySuppressed
Z Hair Academy,Lawrence,KS,0.0,0.0,0.0,0,NaN,NaN,0.0,95.0,...,0.0211,0.0000,0.0105,0.0000,1,0.7286,0.6571,0.1525,NaN,10500
Zane State College,Zanesville,OH,0.0,0.0,0.0,0,NaN,NaN,0.0,2063.0,...,0.0218,0.0000,0.2399,0.5730,1,0.3645,0.3434,0.3185,23800,13960.5
duCret School of Arts,Plainfield,NJ,0.0,0.0,0.0,0,NaN,NaN,0.0,41.0,...,0.0976,0.0000,0.0244,0.4146,1,0.4375,0.5000,0.1250,PrivacySuppressed,PrivacySuppressed
eClips School of Cosmetology and Barbering,Cape Girardeau,MO,0.0,0.0,0.0,0,NaN,NaN,0.0,83.0,...,0.0000,0.0000,0.0000,0.0000,1,0.9496,0.9832,0.3772,PrivacySuppressed,9500