In [1]:
import pandas as pd

In [2]:
movie = pd.read_csv('data/movie.csv')

Read the movie dataset, and pass in a list of the desire columns to the indexing operator:

In [3]:
movie_actor_director = movie[['actor_1_name','actor_2_name','actor_3_name','director_name']]
movie_actor_director.head()

      actor_1_name      actor_2_name          actor_3_name      director_name
0      CCH Pounder  Joel David Moore             Wes Studi      James Cameron
1      Johnny Depp     Orlando Bloom        Jack Davenport     Gore Verbinski
2  Christoph Waltz       Rory Kinner      Stephanie Sigman         Sam Mendes
3        Tom Hardy    Christian Bale  Joseph Gordon-Levitt  Christopher Nolan
4      Doug Walker        Rob Walker                   NaN        Doug Walker

we can save the column names to a list variable first and then pass the list into the indesxing operator of the df.

In [4]:
x = ['actor_1_name','actor_2_name','actor_3_name','director_name']
movie_actor_director = movie[x]
movie_actor_director.head()

      actor_1_name      actor_2_name          actor_3_name      director_name
0      CCH Pounder  Joel David Moore             Wes Studi      James Cameron
1      Johnny Depp     Orlando Bloom        Jack Davenport     Gore Verbinski
2  Christoph Waltz       Rory Kinner      Stephanie Sigman         Sam Mendes
3        Tom Hardy    Christian Bale  Joseph Gordon-Levitt  Christopher Nolan
4      Doug Walker        Rob Walker                   NaN        Doug Walker

In [5]:
movie[['director_name']].head()

       director_name
0      James Cameron
1     Gore Verbinski
2         Sam Mendes
3  Christopher Nolan
4        Doug Walker

if a string is passed, it will return a single dimentional series.

In [6]:
movie['director_name'].head()

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
4          Doug Walker
Name: director_name, dtype: object

 Use get_dtype_counts method to output the number of columns with each specifc data type:

In [7]:
movie = pd.read_csv('data/movie.csv',index_col = 'movie_title')
movie.get_dtype_counts()

float64    13
int64       3
object     11
dtype: int64

We use the dtypes attributes to get the exact data type for each column.

In [8]:
movie.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

Use the select_dtypes method to select only the integer columns

The 'select_dtypes' method takes a list of data types in its include parameter and returns a DataFrame with columns of just those given data dypes

In [9]:
 movie.select_dtypes(include=['int64']).head()

,num_voted_users,cast_total_facebook_likes,movie_facebook_likes
movie_title,,,
Avatar,886204,4834,33000
Pirates of the Caribbean: At World's End,471220,48350,0
Spectre,275868,11700,85000
The Dark Knight Rises,1144337,106759,164000
Star Wars: Episode VII - The Force Awakens,8,143,0

Select all the numeric columns, may simply pass the string number to the include parameter:

In [10]:
movie.select_dtypes(include=['number']).head()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,
Avatar,723.0,178.0,0.0,855.0,1000.0,760505847.0,886204,4834,0.0,3054.0,237000000.0,2009.0,936.0,7.9,1.78,33000
Pirates of the Caribbean: At World's End,302.0,169.0,563.0,1000.0,40000.0,309404152.0,471220,48350,0.0,1238.0,300000000.0,2007.0,5000.0,7.1,2.35,0
Spectre,602.0,148.0,0.0,161.0,11000.0,200074175.0,275868,11700,1.0,994.0,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,813.0,164.0,22000.0,23000.0,27000.0,448130642.0,1144337,106759,0.0,2701.0,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,NaN,131.0,NaN,131.0,NaN,8,143,0.0,NaN,NaN,NaN,12.0,7.1,NaN,0

Filter method is flexible and searches column names. we use 'like' parameter to search for all columns that contain exact 
string.

In [11]:
movie.filter(like='facebook').head()

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
movie_title,,,,,,
Avatar,0.0,855.0,1000.0,4834,936.0,33000
Pirates of the Caribbean: At World's End,563.0,1000.0,40000.0,48350,5000.0,0
Spectre,0.0,161.0,11000.0,11700,393.0,85000
The Dark Knight Rises,22000.0,23000.0,27000.0,106759,23000.0,164000
Star Wars: Episode VII - The Force Awakens,131.0,NaN,131.0,143,12.0,0

The filter method allows columns to be searched through regular expressions with the 'regex' parameter.
Here, We search for all columns that have a digit somewhere in their name.

In [12]:
movie.filter(regex='\d').head()

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
movie_title,,,,,,
Avatar,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
Pirates of the Caribbean: At World's End,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
Spectre,161.0,Rory Kinner,11000.0,Christoph Waltz,Stephanie Sigman,393.0
The Dark Knight Rises,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
Star Wars: Episode VII - The Force Awakens,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0

In [13]:
movie.filter(regex='\d')

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
movie_title,,,,,,
Avatar,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
Pirates of the Caribbean: At World's End,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
Spectre,161.0,Rory Kinner,11000.0,Christoph Waltz,Stephanie Sigman,393.0
The Dark Knight Rises,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
Star Wars: Episode VII - The Force Awakens,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0
John Carter,530.0,Samantha Morton,640.0,Daryl Sabara,Polly Walker,632.0
Spider-Man 3,4000.0,James Franco,24000.0,J.K. Simmons,Kirsten Dunst,11000.0
Tangled,284.0,Donna Murphy,799.0,Brad Garrett,M.C. Gainey,553.0
Avengers: Age of Ultron,19000.0,Robert Downey Jr.,26000.0,Chris Hemsworth,Scarlett Johansson,21000.0
Harry Potter and the Half-Blood Prince,10000.0,Daniel Radcliffe,25000.0,Alan Rickman,Rupert Grint,11000.0
Batman v Superman: Dawn of Justice,2000.0,Lauren Cohan,15000.0,Henry Cavill,Alan D. Purwin,4000.0
Superman Returns,903.0,Marlon Brando,18000.0,Kevin Spacey,Frank Langella,10000.0
Quantum of Solace,393.0,Mathieu Amalric,451.0,Giancarlo Giannini,Rory Kinnear,412.0
Pirates of the Caribbean: Dead Man's Chest,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
The Lone Ranger,1000.0,Ruth Wilson,40000.0,Johnny Depp,Tom Wilkinson,2000.0
Man of Steel,748.0,Christopher Meloni,15000.0,Henry Cavill,Harry Lennix,3000.0
The Chronicles of Narnia: Prince Caspian,201.0,Pierfrancesco Favino,22000.0,Peter Dinklage,Damián Alcázar,216.0
The Avengers,19000.0,Robert Downey Jr.,26000.0,Chris Hemsworth,Scarlett Johansson,21000.0
Pirates of the Caribbean: On Stranger Tides,1000.0,Sam Claflin,40000.0,Johnny Depp,Stephen Graham,11000.0
Men in Black 3,718.0,Michael Stuhlbarg,10000.0,Will Smith,Nicole Scherzinger,816.0
The Hobbit: The Battle of the Five Armies,773.0,Adam Brown,5000.0,Aidan Turner,James Nesbitt,972.0
The Amazing Spider-Man,963.0,Andrew Garfield,15000.0,Emma Stone,Chris Zylka,10000.0
Robin Hood,738.0,William Hurt,891.0,Mark Addy,Scott Grimes,882.0
The Hobbit: The Desolation of Smaug,773.0,Adam Brown,5000.0,Aidan Turner,James Nesbitt,972.0
The Golden Compass,1000.0,Eva Green,16000.0,Christopher Lee,Kristin Scott Thomas,6000.0
King Kong,84.0,Thomas Kretschmann,6000.0,Naomi Watts,Evan Parke,919.0
Titanic,794.0,Kate Winslet,29000.0,Leonardo DiCaprio,Gloria Stuart,14000.0
Captain America: Civil War,11000.0,Scarlett Johansson,21000.0,Robert Downey Jr.,Chris Evans,19000.0
Battleship,627.0,Alexander Skarsgård,14000.0,Liam Neeson,Tadanobu Asano,10000.0
Jurassic World,1000.0,Judy Greer,3000.0,Bryce Dallas Howard,Omar Sy,2000.0
...,...,...,...,...,...,...
Manito,42.0,Panchito Gómez,93.0,Franky G,Casper Martinez,46.0
Rampage,492.0,Katharine Isabelle,986.0,Matt Frewer,Michael Paré,918.0
Slacker,0.0,Richard Linklater,5.0,Tommy Pallotta,Jean Caffeine,0.0
Dutch Kills,9.0,Mikaal Bates,313.0,Tjasa Ferme,Damon Owlia,25.0
Dry Spell,138.0,Suzi Lorraine,370.0,Kristen Seavey,Travis Legge,184.0
Flywheel,4.0,Lisa Arnold,51.0,Shannen Fields,Janet Lee Dapper,49.0
Exeter,265.0,Brittany Curran,630.0,Ashley Tramonte,Lindsay MacDonald,512.0
The Ridges,8.0,Alana Kaniewski,720.0,Robbie Barnes,Brandon Landers,19.0
The Puffy Chair,10.0,Katie Aselton,830.0,Mark Duplass,Bari Hyman,224.0
Stories of Our Lives,4.0,Olwenya Maina,147.0,Paul Ogola,Mugambi Nthiga,19.0
Breaking Upwards,211.0,Heather Burns,331.0,Zoe Lister-Jones,Ebon Moss-Bachrach,212.0
All Superheroes Must Die,86.0,Jason Trost,407.0,Sean Whalen,Nick Principe,91.0
Pink Flamingos,105.0,Mink Stole,462.0,Divine,Edith Massey,143.0
Clean,45.0,Béatrice Dalle,576.0,Maggie Cheung,Don McKellar,133.0
The Circle,0.0,Nargess Mamizadeh,5.0,Fereshteh Sadre Orafaiy,Mojgan Faramarzi,0.0
Tin Can Man,0.0,Michael Parle,10.0,Patrick O'Donnell,Emma Eliza Regan,5.0
The Cure,6.0,Anna Nakagawa,89.0,Kôji Yakusho,Denden,13.0
On the Downlow,12.0,Michael Cortez,21.0,Tatiana Suarez-Pico,Eric Ambriz,20.0
Sanctuary; Quite a Conundrum,84.0,Joe Coffey,785.0,Julianna Pitt,John Lucas,98.0
Bang,152.0,Stanley B. Herman,789.0,Peter Greene,James Noble,194.0
Primer,8.0,David Sullivan,291.0,Shane Carruth,Casey Gooden,45.0
Cavite,0.0,Edgar Tancangco,0.0,Ian Gamazon,Quynn Ton,0.0
El Mariachi,6.0,Peter Marquardt,121.0,Carlos Gallardo,Consuelo Gómez,20.0
The Mongol King,2.0,John Considine,45.0,Richard Jewell,Sara Stepnicka,44.0
Newlyweds,133.0,Caitlin FitzGerald,296.0,Kerry Bishé,Daniella Pineda,205.0
Signed Sealed Delivered,318.0,Daphne Zuniga,637.0,Eric Mabius,Crystal Lowe,470.0
The Following,319.0,Valorie Curry,841.0,Natalie Zea,Sam Underwood,593.0
A Plague So Pleasant,0.0,Maxwell Moody,0.0,Eva Boehnke,David Chandler,0.0
Shanghai Calling,489.0,Daniel Henney,946.0,Alan Ruck,Eliza Coupe,719.0
My Date with Drew,16.0,Brian Herzlinger,86.0,John August,Jon Gunn,23.0

In [14]:
movie.filter(items=['actor_1_name','anycolumnname'])

                                                        actor_1_name
movie_title
Avatar                                                   CCH Pounder
Pirates of the Caribbean: At World's End                 Johnny Depp
Spectre                                              Christoph Waltz
The Dark Knight Rises                                      Tom Hardy
Star Wars: Episode VII - The Force Awakens               Doug Walker
John Carter                                             Daryl Sabara
Spider-Man 3                                            J.K. Simmons
Tangled                                                 Brad Garrett
Avengers: Age of Ultron                              Chris Hemsworth
Harry Potter and the Half-Blood Prince                  Alan Rickman
Batman v Superman: Dawn of Justice                      Henry Cavill
Superman Returns                                        Kevin Spacey
Quantum of Solace                                 Giancarlo Giannini
Pirates of the Caribbean: Dead Man's Chest               Johnny Depp
The Lone Ranger                                          Johnny Depp
Man of Steel                                            Henry Cavill
The Chronicles of Narnia: Prince Caspian              Peter Dinklage
The Avengers                                         Chris Hemsworth
Pirates of the Caribbean: On Stranger Tides              Johnny Depp
Men in Black 3                                            Will Smith
The Hobbit: The Battle of the Five Armies               Aidan Turner
The Amazing Spider-Man                                    Emma Stone
Robin Hood                                                 Mark Addy
The Hobbit: The Desolation of Smaug                     Aidan Turner
The Golden Compass                                   Christopher Lee
King Kong                                                Naomi Watts
Titanic                                            Leonardo DiCaprio
Captain America: Civil War                         Robert Downey Jr.
Battleship                                               Liam Neeson
Jurassic World                                   Bryce Dallas Howard
...                                                              ...
Manito                                                      Franky G
Rampage                                                  Matt Frewer
Slacker                                               Tommy Pallotta
Dutch Kills                                              Tjasa Ferme
Dry Spell                                             Kristen Seavey
Flywheel                                              Shannen Fields
Exeter                                               Ashley Tramonte
The Ridges                                             Robbie Barnes
The Puffy Chair                                         Mark Duplass
Stories of Our Lives                                      Paul Ogola
Breaking Upwards                                    Zoe Lister-Jones
All Superheroes Must Die                                 Sean Whalen
Pink Flamingos                                                Divine
Clean                                                  Maggie Cheung
The Circle                                   Fereshteh Sadre Orafaiy
Tin Can Man                                        Patrick O'Donnell
The Cure                                                Kôji Yakusho
On the Downlow                                   Tatiana Suarez-Pico
Sanctuary; Quite a Conundrum                           Julianna Pitt
Bang                                                    Peter Greene
Primer                                                 Shane Carruth
Cavite                                                   Ian Gamazon
El Mariachi                                          Carlos Gallardo
The Mongol King                                       Richard Jewell
Newlyweds                                                Kerry Bishé
Signed Sealed Delivered                                  Eric Mabius
The Following                                            Natalie Zea
A Plague So Pleasant                                     Eva Boehnke
Shanghai Calling                                           Alan Ruck
My Date with Drew                                        John August

[4916 rows x 1 columns]

In [15]:
movie = pd.read_csv('data/movie.csv')
movie.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinner,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [16]:
movie.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [17]:
disc_core = ['movie_title','title_year','content_rating','genres']
disc_people = ['director_name','actor_1_name','actor_2_name','actor_3_name']
disc_other = ['color','country','language','plot_keywords','movie_imdb_link']
cont_fb = ['director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes',
            'actor_3_facebook_likes','cast_total_facebook_likes','movie_facebook_likes']
cont_finance = ['budget','gross']
cont_num_reviews = ['num_voted_users','num_user_for_reviews','num_critic_for_reviews']
cont_other = ['imdb_score','duration','aspect_ratio','facenumber_in_poster']

In [18]:
new_col_order = disc_core + disc_people + \
disc_other + cont_fb + \
cont_finance + cont_num_reviews + \
cont_other
set(movie.columns) == set(new_col_order)

True

In [19]:
movie2 = movie[new_col_order]
movie2.head()

,movie_title,title_year,content_rating,genres,director_name,actor_1_name,actor_2_name,actor_3_name,color,country,...,movie_facebook_likes,budget,gross,num_voted_users,num_user_for_reviews,num_critic_for_reviews,imdb_score,duration,aspect_ratio,facenumber_in_poster
0,Avatar,2009.0,PG-13,Action|Adventure|Fantasy|Sci-Fi,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Color,USA,...,33000,237000000.0,760505847.0,886204,3054.0,723.0,7.9,178.0,1.78,0.0
1,Pirates of the Caribbean: At World's End,2007.0,PG-13,Action|Adventure|Fantasy,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Color,USA,...,0,300000000.0,309404152.0,471220,1238.0,302.0,7.1,169.0,2.35,0.0
2,Spectre,2015.0,PG-13,Action|Adventure|Thriller,Sam Mendes,Christoph Waltz,Rory Kinner,Stephanie Sigman,Color,UK,...,85000,245000000.0,200074175.0,275868,994.0,602.0,6.8,148.0,2.35,1.0
3,The Dark Knight Rises,2012.0,PG-13,Action|Thriller,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Color,USA,...,164000,250000000.0,448130642.0,1144337,2701.0,813.0,8.5,164.0,2.35,0.0
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,Documentary,Doug Walker,Doug Walker,Rob Walker,NaN,NaN,NaN,...,0,NaN,NaN,8,NaN,NaN,7.1,NaN,NaN,0.0

In [20]:
movie = pd.read_csv('data/movie.csv')
movie.shape

(4916, 28)

In [21]:
movie.size

137648

In [22]:
movie.ndim

2

In [23]:
len(movie)

4916

In [24]:
movie.count()

color                        4897
director_name                4814
num_critic_for_reviews       4867
duration                     4901
director_facebook_likes      4814
actor_3_facebook_likes       4893
actor_2_name                 4903
actor_1_facebook_likes       4909
gross                        4054
genres                       4916
actor_1_name                 4909
movie_title                  4916
num_voted_users              4916
cast_total_facebook_likes    4916
actor_3_name                 4893
facenumber_in_poster         4903
plot_keywords                4764
movie_imdb_link              4916
num_user_for_reviews         4895
language                     4904
country                      4911
content_rating               4616
budget                       4432
title_year                   4810
actor_2_facebook_likes       4903
imdb_score                   4916
aspect_ratio                 4590
movie_facebook_likes         4916
dtype: int64

In [25]:
movie.min()

num_critic_for_reviews          1.00
duration                        7.00
director_facebook_likes         0.00
actor_3_facebook_likes          0.00
actor_1_facebook_likes          0.00
gross                         162.00
num_voted_users                 5.00
cast_total_facebook_likes       0.00
facenumber_in_poster            0.00
num_user_for_reviews            1.00
budget                        218.00
title_year                   1916.00
actor_2_facebook_likes          0.00
imdb_score                      1.60
aspect_ratio                    1.18
movie_facebook_likes            0.00
dtype: float64

In [26]:
movie.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,49.000000,93.000000,7.000000,132.000000,607.000000,5.019656e+06,8.361750e+03,1394.750000,0.000000,64.000000,6.000000e+06,1999.000000,277.000000,5.800000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000
75%,191.000000,118.000000,189.750000,633.000000,11000.000000,6.110841e+07,9.377275e+04,13616.750000,2.000000,320.500000,4.300000e+07,2011.000000,912.000000,7.200000,2.350000,2000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [27]:
movie.describe(percentiles=[.01,.3,.99])

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
1%,2.000000,43.000000,0.000000,0.000000,6.080000,8.474800e+03,5.300000e+01,6.000000,0.000000,1.940000,6.000000e+04,1951.000000,0.000000,3.100000,1.330000,0.000000
30%,60.000000,95.000000,11.000000,176.000000,694.000000,7.914069e+06,1.186450e+04,1684.500000,0.000000,80.000000,8.000000e+06,2000.000000,345.000000,6.000000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000
99%,546.680000,189.000000,16000.000000,11000.000000,44920.000000,3.264128e+08,6.815846e+05,62413.900000,8.000000,1999.240000,2.000000e+08,2016.000000,17000.000000,8.500000,4.000000,93850.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [28]:
movie.min(skipna=False)#

num_critic_for_reviews       NaN
duration                     NaN
director_facebook_likes      NaN
actor_3_facebook_likes       NaN
actor_1_facebook_likes       NaN
gross                        NaN
num_voted_users              5.0
cast_total_facebook_likes    0.0
facenumber_in_poster         NaN
num_user_for_reviews         NaN
budget                       NaN
title_year                   NaN
actor_2_facebook_likes       NaN
imdb_score                   1.6
aspect_ratio                 NaN
movie_facebook_likes         0.0
dtype: float64

In [29]:
movie.min(skipna=True) #By default skipna = True

num_critic_for_reviews          1.00
duration                        7.00
director_facebook_likes         0.00
actor_3_facebook_likes          0.00
actor_1_facebook_likes          0.00
gross                         162.00
num_voted_users                 5.00
cast_total_facebook_likes       0.00
facenumber_in_poster            0.00
num_user_for_reviews            1.00
budget                        218.00
title_year                   1916.00
actor_2_facebook_likes          0.00
imdb_score                      1.60
aspect_ratio                    1.18
movie_facebook_likes            0.00
dtype: float64

In [30]:
movie = pd.read_csv('data/movie.csv')
movie.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinner,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [31]:
movie = pd.read_csv('data/movie.csv')
movie.isnull().head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,True,False,True,True,False,True,False,False,True,False,...,True,True,True,True,True,True,False,False,True,False

In [32]:
movie.isnull().sum().head()

color                       19
director_name              102
num_critic_for_reviews      49
duration                    15
director_facebook_likes    102
dtype: int64

In [33]:
movie.isnull().sum().sum()

2654

In [34]:
movie.isnull().any().any()

True

In [35]:
movie.isnull().get_dtype_counts()

bool    28
dtype: int64

In [36]:
movie[['color','movie_title','color']].max()

Series([], dtype: float64)

In [37]:
movie.select_dtypes(['object']).fillna('').max()

color                                                          Color
director_name                                          Étienne Faure
actor_2_name                                           Zubaida Sahar
genres                                                       Western
actor_1_name                                           Óscar Jaenada
movie_title                                                 Æon Flux
actor_3_name                                           Óscar Jaenada
plot_keywords                                    zombie|zombie spoof
movie_imdb_link    http://www.imdb.com/title/tt5574490/?ref_=fn_t...
language                                                        Zulu
country                                                 West Germany
content_rating                                                     X
dtype: object

In [38]:
movie.select_dtypes(['object']) \
 .fillna('') \
 .max()

color                                                          Color
director_name                                          Étienne Faure
actor_2_name                                           Zubaida Sahar
genres                                                       Western
actor_1_name                                           Óscar Jaenada
movie_title                                                 Æon Flux
actor_3_name                                           Óscar Jaenada
plot_keywords                                    zombie|zombie spoof
movie_imdb_link    http://www.imdb.com/title/tt5574490/?ref_=fn_t...
language                                                        Zulu
country                                                 West Germany
content_rating                                                     X
dtype: object

In [39]:
 college = pd.read_csv('data/college.csv')

In [40]:
college.head()

,INSTNM,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
0,Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
1,University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
2,Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
3,University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
4,Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

In [41]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')
college_ugds_ = college.filter(like='UGDS_')
college_ugds_.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [42]:
 college_ugds_ + .00501

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.03831,0.94031,0.01051,0.00691,0.00741,0.00691,0.00501,0.01091,0.01881
University of Alabama at Birmingham,0.59721,0.26501,0.03331,0.05681,0.00721,0.00571,0.04181,0.02291,0.01501
Amridge University,0.30401,0.42421,0.01191,0.00841,0.00501,0.00501,0.00501,0.00501,0.27651
University of Alabama in Huntsville,0.70381,0.13051,0.04321,0.04261,0.01931,0.00521,0.02221,0.03821,0.04001
Alabama State University,0.02081,0.92581,0.01711,0.00691,0.00601,0.00561,0.01481,0.02931,0.01871
The University of Alabama,0.78751,0.11691,0.03981,0.01561,0.00881,0.00591,0.03111,0.03181,0.00761
Central Alabama Community College,0.73051,0.26631,0.00941,0.00751,0.00941,0.00501,0.00501,0.00501,0.00691
Athens State University,0.78731,0.12501,0.02411,0.01031,0.02071,0.00601,0.02241,0.01071,0.03841
Auburn University at Montgomery,0.53781,0.34261,0.01241,0.02711,0.00941,0.00661,0.03471,0.04471,0.02961
Auburn University,0.85571,0.07541,0.02981,0.02771,0.01241,0.00501,0.00501,0.01501,0.01901
Birmingham Southern College,0.80331,0.11521,0.02451,0.05671,0.01521,0.00501,0.01011,0.00501,0.01011
Chattahoochee Valley Community College,0.47111,0.44221,0.05421,0.01771,0.00731,0.00851,0.02011,0.00501,0.01891
Concordia College Alabama,0.03301,0.88081,0.04231,0.01431,0.00501,0.00501,0.00811,0.05161,0.00501
South University-Montgomery,0.30961,0.61041,0.02031,0.02031,0.02031,0.01461,0.00501,0.00691,0.03761
Enterprise State Community College,0.64581,0.24851,0.05591,0.02521,0.01311,0.00791,0.03041,0.00621,0.01191
James H Faulkner State Community College,0.70291,0.23091,0.03701,0.01341,0.02271,0.00641,0.02021,0.00571,0.00591
Faulkner University,0.39241,0.51871,0.03081,0.00921,0.01131,0.00631,0.02231,0.02321,0.03081
Gadsden State Community College,0.69711,0.21261,0.03551,0.00971,0.01781,0.00681,0.02351,0.02001,0.02191
New Beginning College of Cosmetology,0.90071,0.03981,0.07461,0.00501,0.00501,0.00501,0.00501,0.00501,0.00501
George C Wallace State Community College-Dothan,0.63231,0.32901,0.02711,0.01221,0.00991,0.00591,0.01761,0.00501,0.00591
George C Wallace State Community College-Hanceville,0.86801,0.06621,0.04121,0.01151,0.01391,0.00501,0.00501,0.01091,0.02331
George C Wallace State Community College-Selma,0.20061,0.74991,0.00761,0.00901,0.00631,0.00501,0.00831,0.00901,0.04931
Herzing University-Birmingham,0.35931,0.53151,0.02161,0.01161,0.00501,0.00501,0.06131,0.00501,0.04471
Huntingdon College,0.64381,0.20431,0.03021,0.01281,0.01721,0.00671,0.03111,0.01111,0.08771
Heritage Christian University,0.74691,0.11791,0.05341,0.00501,0.03731,0.02111,0.00501,0.02111,0.03731
J F Drake State Community and Technical College,0.33871,0.60151,0.02961,0.01321,0.01631,0.00601,0.02351,0.00501,0.01121
Jacksonville State University,0.68841,0.24321,0.01821,0.01051,0.01221,0.00601,0.00501,0.02841,0.03301
Jefferson Davis Community College,0.59071,0.30321,0.01271,0.03021,0.03021,0.00501,0.02341,0.00501,0.04471
Jefferson State Community College,0.67461,0.22961,0.05361,0.02331,0.00741,0.00581,0.03511,0.01041,0.00511
John C Calhoun State Community College,0.65781,0.19901,0.04851,0.03071,0.02321,0.00561,0.04781,0.01121,0.02121
...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Piscataway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Utah County Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
L'esprit Academy - Royal Oak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
National Career Institute - Jersey City Branch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Cobb Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Morrow Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Roswell Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Douglasville Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Lithonia Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Savannah Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Augusta Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Columbus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Columbia Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Charleston Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Irving,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Katy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Northwest Houston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Plano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Cedar Hill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-North Dallas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-San Antonio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Stafford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WestMed College - Merced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vantage College,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAE Institute of Technology San Francisco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rasmussen College - Overland Park,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
National Personal Training Institute of Cleveland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bay Area Medical Academy - San Jose Satellite Location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Excel Learning Center-San Antonio South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
 (college_ugds_ + .00501) // .01

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,3.0,94.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
University of Alabama at Birmingham,59.0,26.0,3.0,5.0,0.0,0.0,4.0,2.0,1.0
Amridge University,30.0,42.0,1.0,0.0,0.0,0.0,0.0,0.0,27.0
University of Alabama in Huntsville,70.0,13.0,4.0,4.0,1.0,0.0,2.0,3.0,4.0
Alabama State University,2.0,92.0,1.0,0.0,0.0,0.0,1.0,2.0,1.0
The University of Alabama,78.0,11.0,3.0,1.0,0.0,0.0,3.0,3.0,0.0
Central Alabama Community College,73.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Athens State University,78.0,12.0,2.0,1.0,2.0,0.0,2.0,1.0,3.0
Auburn University at Montgomery,53.0,34.0,1.0,2.0,0.0,0.0,3.0,4.0,2.0
Auburn University,85.0,7.0,2.0,2.0,1.0,0.0,0.0,1.0,1.0
Birmingham Southern College,80.0,11.0,2.0,5.0,1.0,0.0,1.0,0.0,1.0
Chattahoochee Valley Community College,47.0,44.0,5.0,1.0,0.0,0.0,2.0,0.0,1.0
Concordia College Alabama,3.0,88.0,4.0,1.0,0.0,0.0,0.0,5.0,0.0
South University-Montgomery,30.0,61.0,2.0,2.0,2.0,1.0,0.0,0.0,3.0
Enterprise State Community College,64.0,24.0,5.0,2.0,1.0,0.0,3.0,0.0,1.0
James H Faulkner State Community College,70.0,23.0,3.0,1.0,2.0,0.0,2.0,0.0,0.0
Faulkner University,39.0,51.0,3.0,0.0,1.0,0.0,2.0,2.0,3.0
Gadsden State Community College,69.0,21.0,3.0,0.0,1.0,0.0,2.0,2.0,2.0
New Beginning College of Cosmetology,90.0,3.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0
George C Wallace State Community College-Dothan,63.0,32.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0
George C Wallace State Community College-Hanceville,86.0,6.0,4.0,1.0,1.0,0.0,0.0,1.0,2.0
George C Wallace State Community College-Selma,20.0,74.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
Herzing University-Birmingham,35.0,53.0,2.0,1.0,0.0,0.0,6.0,0.0,4.0
Huntingdon College,64.0,20.0,3.0,1.0,1.0,0.0,3.0,1.0,8.0
Heritage Christian University,74.0,11.0,5.0,0.0,3.0,2.0,0.0,2.0,3.0
J F Drake State Community and Technical College,33.0,60.0,2.0,1.0,1.0,0.0,2.0,0.0,1.0
Jacksonville State University,68.0,24.0,1.0,1.0,1.0,0.0,0.0,2.0,3.0
Jefferson Davis Community College,59.0,30.0,1.0,3.0,3.0,0.0,2.0,0.0,4.0
Jefferson State Community College,67.0,22.0,5.0,2.0,0.0,0.0,3.0,1.0,0.0
John C Calhoun State Community College,65.0,19.0,4.0,3.0,2.0,0.0,4.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Piscataway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Utah County Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
L'esprit Academy - Royal Oak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
National Career Institute - Jersey City Branch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Cobb Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Morrow Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Roswell Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Douglasville Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Lithonia Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Savannah Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Augusta Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Columbus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Columbia Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Charleston Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Irving,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Katy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Northwest Houston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Plano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Cedar Hill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-North Dallas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-San Antonio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Stafford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WestMed College - Merced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vantage College,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAE Institute of Technology San Francisco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rasmussen College - Overland Park,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
National Personal Training Institute of Cleveland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bay Area Medical Academy - San Jose Satellite Location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Excel Learning Center-San Antonio South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
college_ugds_op_round = (college_ugds_ + .00501) // .01 / 100
college_ugds_op_round.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.03,0.94,0.01,0.00,0.00,0.0,0.00,0.01,0.01
University of Alabama at Birmingham,0.59,0.26,0.03,0.05,0.00,0.0,0.04,0.02,0.01
Amridge University,0.30,0.42,0.01,0.00,0.00,0.0,0.00,0.00,0.27
University of Alabama in Huntsville,0.70,0.13,0.04,0.04,0.01,0.0,0.02,0.03,0.04
Alabama State University,0.02,0.92,0.01,0.00,0.00,0.0,0.01,0.02,0.01

In [45]:
 college_ugds_round = (college_ugds_ + .00001).round(2)

In [46]:
college_ugds_op_round.equals(college_ugds_round)

True

In [47]:
college_ugds_op_round_methods = college_ugds_.add(.00501).floordiv(.01).div(100)

In [48]:
college_ugds_op_round_methods.equals(college_ugds_op_round)

True

In [49]:
import numpy as np
np.nan ==np.nan

False

In [50]:
None == None

True

In [51]:
np.nan > 5

False

In [52]:
np.nan != 5

True

In [53]:
college = pd.read_csv('data/college.csv',index_col='INSTNM')
college_ugds_ = college.filter(like='UGDS_')

In [54]:
0.019

0.019

In [55]:
college_ugds_

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137
The University of Alabama,0.7825,0.1119,0.0348,0.0106,0.0038,0.0009,0.0261,0.0268,0.0026
Central Alabama Community College,0.7255,0.2613,0.0044,0.0025,0.0044,0.0000,0.0000,0.0000,0.0019
Athens State University,0.7823,0.1200,0.0191,0.0053,0.0157,0.0010,0.0174,0.0057,0.0334
Auburn University at Montgomery,0.5328,0.3376,0.0074,0.0221,0.0044,0.0016,0.0297,0.0397,0.0246
Auburn University,0.8507,0.0704,0.0248,0.0227,0.0074,0.0000,0.0000,0.0100,0.0140
Birmingham Southern College,0.7983,0.1102,0.0195,0.0517,0.0102,0.0000,0.0051,0.0000,0.0051
Chattahoochee Valley Community College,0.4661,0.4372,0.0492,0.0127,0.0023,0.0035,0.0151,0.0000,0.0139
Concordia College Alabama,0.0280,0.8758,0.0373,0.0093,0.0000,0.0000,0.0031,0.0466,0.0000
South University-Montgomery,0.3046,0.6054,0.0153,0.0153,0.0153,0.0096,0.0000,0.0019,0.0326
Enterprise State Community College,0.6408,0.2435,0.0509,0.0202,0.0081,0.0029,0.0254,0.0012,0.0069
James H Faulkner State Community College,0.6979,0.2259,0.0320,0.0084,0.0177,0.0014,0.0152,0.0007,0.0009
Faulkner University,0.3874,0.5137,0.0258,0.0042,0.0063,0.0013,0.0173,0.0182,0.0258
Gadsden State Community College,0.6921,0.2076,0.0305,0.0047,0.0128,0.0018,0.0185,0.0150,0.0169
New Beginning College of Cosmetology,0.8957,0.0348,0.0696,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
George C Wallace State Community College-Dothan,0.6273,0.3240,0.0221,0.0072,0.0049,0.0009,0.0126,0.0000,0.0009
George C Wallace State Community College-Hanceville,0.8630,0.0612,0.0362,0.0065,0.0089,0.0000,0.0000,0.0059,0.0183
George C Wallace State Community College-Selma,0.1956,0.7449,0.0026,0.0040,0.0013,0.0000,0.0033,0.0040,0.0443
Herzing University-Birmingham,0.3543,0.5265,0.0166,0.0066,0.0000,0.0000,0.0563,0.0000,0.0397
Huntingdon College,0.6388,0.1993,0.0252,0.0078,0.0122,0.0017,0.0261,0.0061,0.0827
Heritage Christian University,0.7419,0.1129,0.0484,0.0000,0.0323,0.0161,0.0000,0.0161,0.0323
J F Drake State Community and Technical College,0.3337,0.5965,0.0246,0.0082,0.0113,0.0010,0.0185,0.0000,0.0062
Jacksonville State University,0.6834,0.2382,0.0132,0.0055,0.0072,0.0010,0.0000,0.0234,0.0280
Jefferson Davis Community College,0.5857,0.2982,0.0077,0.0252,0.0252,0.0000,0.0184,0.0000,0.0397
Jefferson State Community College,0.6696,0.2246,0.0486,0.0183,0.0024,0.0008,0.0301,0.0054,0.0001
John C Calhoun State Community College,0.6528,0.1940,0.0435,0.0257,0.0182,0.0006,0.0428,0.0062,0.0162
...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Piscataway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Utah County Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
L'esprit Academy - Royal Oak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
National Career Institute - Jersey City Branch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Cobb Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Morrow Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Roswell Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Douglasville Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Lithonia Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Savannah Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Augusta Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Columbus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Columbia Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Charleston Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Irving,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Katy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Northwest Houston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Plano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Cedar Hill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-North Dallas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-San Antonio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Strayer University-Stafford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WestMed College - Merced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vantage College,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAE Institute of Technology San Francisco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rasmussen College - Overland Park,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
National Personal Training Institute of Cleveland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bay Area Medical Academy - San Jose Satellite Location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Excel Learning Center-San Antonio South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#Compare each element to a scalar values:

In [56]:
college_ugds_ == 0.0019

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,False,False,False,True,False,True,False,False,False
University of Alabama at Birmingham,False,False,False,False,False,False,False,False,False
Amridge University,False,False,False,False,False,False,False,False,False
University of Alabama in Huntsville,False,False,False,False,False,False,False,False,False
Alabama State University,False,False,False,True,False,False,False,False,False
The University of Alabama,False,False,False,False,False,False,False,False,False
Central Alabama Community College,False,False,False,False,False,False,False,False,True
Athens State University,False,False,False,False,False,False,False,False,False
Auburn University at Montgomery,False,False,False,False,False,False,False,False,False
Auburn University,False,False,False,False,False,False,False,False,False
Birmingham Southern College,False,False,False,False,False,False,False,False,False
Chattahoochee Valley Community College,False,False,False,False,False,False,False,False,False
Concordia College Alabama,False,False,False,False,False,False,False,False,False
South University-Montgomery,False,False,False,False,False,False,False,True,False
Enterprise State Community College,False,False,False,False,False,False,False,False,False
James H Faulkner State Community College,False,False,False,False,False,False,False,False,False
Faulkner University,False,False,False,False,False,False,False,False,False
Gadsden State Community College,False,False,False,False,False,False,False,False,False
New Beginning College of Cosmetology,False,False,False,False,False,False,False,False,False
George C Wallace State Community College-Dothan,False,False,False,False,False,False,False,False,False
George C Wallace State Community College-Hanceville,False,False,False,False,False,False,False,False,False
George C Wallace State Community College-Selma,False,False,False,False,False,False,False,False,False
Herzing University-Birmingham,False,False,False,False,False,False,False,False,False
Huntingdon College,False,False,False,False,False,False,False,False,False
Heritage Christian University,False,False,False,False,False,False,False,False,False
J F Drake State Community and Technical College,False,False,False,False,False,False,False,False,False
Jacksonville State University,False,False,False,False,False,False,False,False,False
Jefferson Davis Community College,False,False,False,False,False,False,False,False,False
Jefferson State Community College,False,False,False,False,False,False,False,False,False
John C Calhoun State Community College,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,False,False,False,False,False,False,False,False,False
Strayer University-Piscataway,False,False,False,False,False,False,False,False,False
Utah County Campus,False,False,False,False,False,False,False,False,False
L'esprit Academy - Royal Oak,False,False,False,False,False,False,False,False,False
National Career Institute - Jersey City Branch,False,False,False,False,False,False,False,False,False
Strayer University-Cobb Campus,False,False,False,False,False,False,False,False,False
Strayer University-Morrow Campus,False,False,False,False,False,False,False,False,False
Strayer University-Roswell Campus,False,False,False,False,False,False,False,False,False
Strayer University-Douglasville Campus,False,False,False,False,False,False,False,False,False
Strayer University-Lithonia Campus,False,False,False,False,False,False,False,False,False
Strayer University-Savannah Campus,False,False,False,False,False,False,False,False,False
Strayer University-Augusta Campus,False,False,False,False,False,False,False,False,False
Strayer University-Columbus,False,False,False,False,False,False,False,False,False
Strayer University-Columbia Campus,False,False,False,False,False,False,False,False,False
Strayer University-Charleston Campus,False,False,False,False,False,False,False,False,False
Strayer University-Irving,False,False,False,False,False,False,False,False,False
Strayer University-Katy,False,False,False,False,False,False,False,False,False
Strayer University-Northwest Houston,False,False,False,False,False,False,False,False,False
Strayer University-Plano,False,False,False,False,False,False,False,False,False
Strayer University-Cedar Hill,False,False,False,False,False,False,False,False,False
Strayer University-North Dallas,False,False,False,False,False,False,False,False,False
Strayer University-San Antonio,False,False,False,False,False,False,False,False,False
Strayer University-Stafford,False,False,False,False,False,False,False,False,False
WestMed College - Merced,False,False,False,False,False,False,False,False,False
Vantage College,False,False,False,False,False,False,False,False,False
SAE Institute of Technology San Francisco,False,False,False,False,False,False,False,False,False
Rasmussen College - Overland Park,False,False,False,False,False,False,False,False,False
National Personal Training Institute of Cleveland,False,False,False,False,False,False,False,False,False
Bay Area Medical Academy - San Jose Satellite Location,False,False,False,False,False,False,False,False,False
Excel Learning Center-San Antonio South,False,False,False,False,False,False,False,False,False

In [57]:
college_self_compare = college_ugds_ == college_ugds_
college_self_compare.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,True,True,True,True,True,True,True,True,True
University of Alabama at Birmingham,True,True,True,True,True,True,True,True,True
Amridge University,True,True,True,True,True,True,True,True,True
University of Alabama in Huntsville,True,True,True,True,True,True,True,True,True
Alabama State University,True,True,True,True,True,True,True,True,True

#Using the 'all' method to determine if each columns contains only True values yeilds an unexpected result:

In [58]:
college_self_compare.all()

UGDS_WHITE    False
UGDS_BLACK    False
UGDS_HISP     False
UGDS_ASIAN    False
UGDS_AIAN     False
UGDS_NHPI     False
UGDS_2MOR     False
UGDS_NRA      False
UGDS_UNKN     False
dtype: bool

In [59]:
(college_ugds_ == np.nan).sum()

UGDS_WHITE    0
UGDS_BLACK    0
UGDS_HISP     0
UGDS_ASIAN    0
UGDS_AIAN     0
UGDS_NHPI     0
UGDS_2MOR     0
UGDS_NRA      0
UGDS_UNKN     0
dtype: int64

The primary way to count missing values the isnull method:

In [60]:
college_ugds_.isnull().sum()

UGDS_WHITE    661
UGDS_BLACK    661
UGDS_HISP     661
UGDS_ASIAN    661
UGDS_AIAN     661
UGDS_NHPI     661
UGDS_2MOR     661
UGDS_NRA      661
UGDS_UNKN     661
dtype: int64

The correct way to compare two entire DataFrames with one another is not with the equals operator
but with the equals method:

In [61]:
college_ugds_.equals(college_ugds_)

True

In [62]:
college_ugds_.eq(.0019) # same as college_ugds_ == .0019

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,False,False,False,True,False,True,False,False,False
University of Alabama at Birmingham,False,False,False,False,False,False,False,False,False
Amridge University,False,False,False,False,False,False,False,False,False
University of Alabama in Huntsville,False,False,False,False,False,False,False,False,False
Alabama State University,False,False,False,True,False,False,False,False,False
The University of Alabama,False,False,False,False,False,False,False,False,False
Central Alabama Community College,False,False,False,False,False,False,False,False,True
Athens State University,False,False,False,False,False,False,False,False,False
Auburn University at Montgomery,False,False,False,False,False,False,False,False,False
Auburn University,False,False,False,False,False,False,False,False,False
Birmingham Southern College,False,False,False,False,False,False,False,False,False
Chattahoochee Valley Community College,False,False,False,False,False,False,False,False,False
Concordia College Alabama,False,False,False,False,False,False,False,False,False
South University-Montgomery,False,False,False,False,False,False,False,True,False
Enterprise State Community College,False,False,False,False,False,False,False,False,False
James H Faulkner State Community College,False,False,False,False,False,False,False,False,False
Faulkner University,False,False,False,False,False,False,False,False,False
Gadsden State Community College,False,False,False,False,False,False,False,False,False
New Beginning College of Cosmetology,False,False,False,False,False,False,False,False,False
George C Wallace State Community College-Dothan,False,False,False,False,False,False,False,False,False
George C Wallace State Community College-Hanceville,False,False,False,False,False,False,False,False,False
George C Wallace State Community College-Selma,False,False,False,False,False,False,False,False,False
Herzing University-Birmingham,False,False,False,False,False,False,False,False,False
Huntingdon College,False,False,False,False,False,False,False,False,False
Heritage Christian University,False,False,False,False,False,False,False,False,False
J F Drake State Community and Technical College,False,False,False,False,False,False,False,False,False
Jacksonville State University,False,False,False,False,False,False,False,False,False
Jefferson Davis Community College,False,False,False,False,False,False,False,False,False
Jefferson State Community College,False,False,False,False,False,False,False,False,False
John C Calhoun State Community College,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,False,False,False,False,False,False,False,False,False
Strayer University-Piscataway,False,False,False,False,False,False,False,False,False
Utah County Campus,False,False,False,False,False,False,False,False,False
L'esprit Academy - Royal Oak,False,False,False,False,False,False,False,False,False
National Career Institute - Jersey City Branch,False,False,False,False,False,False,False,False,False
Strayer University-Cobb Campus,False,False,False,False,False,False,False,False,False
Strayer University-Morrow Campus,False,False,False,False,False,False,False,False,False
Strayer University-Roswell Campus,False,False,False,False,False,False,False,False,False
Strayer University-Douglasville Campus,False,False,False,False,False,False,False,False,False
Strayer University-Lithonia Campus,False,False,False,False,False,False,False,False,False
Strayer University-Savannah Campus,False,False,False,False,False,False,False,False,False
Strayer University-Augusta Campus,False,False,False,False,False,False,False,False,False
Strayer University-Columbus,False,False,False,False,False,False,False,False,False
Strayer University-Columbia Campus,False,False,False,False,False,False,False,False,False
Strayer University-Charleston Campus,False,False,False,False,False,False,False,False,False
Strayer University-Irving,False,False,False,False,False,False,False,False,False
Strayer University-Katy,False,False,False,False,False,False,False,False,False
Strayer University-Northwest Houston,False,False,False,False,False,False,False,False,False
Strayer University-Plano,False,False,False,False,False,False,False,False,False
Strayer University-Cedar Hill,False,False,False,False,False,False,False,False,False
Strayer University-North Dallas,False,False,False,False,False,False,False,False,False
Strayer University-San Antonio,False,False,False,False,False,False,False,False,False
Strayer University-Stafford,False,False,False,False,False,False,False,False,False
WestMed College - Merced,False,False,False,False,False,False,False,False,False
Vantage College,False,False,False,False,False,False,False,False,False
SAE Institute of Technology San Francisco,False,False,False,False,False,False,False,False,False
Rasmussen College - Overland Park,False,False,False,False,False,False,False,False,False
National Personal Training Institute of Cleveland,False,False,False,False,False,False,False,False,False
Bay Area Medical Academy - San Jose Satellite Location,False,False,False,False,False,False,False,False,False
Excel Learning Center-San Antonio South,False,False,False,False,False,False,False,False,False

In [63]:
from pandas.testing import assert_frame_equal
assert_frame_equal(college_ugds_, college_ugds_)

The columns that begin with UGDS_ represent the
percentage of the undergraduate students of a particular race. Use the filter
method to select these columns

In [64]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')
college_ugds_ = college.filter(like='UGDS_')
college_ugds_.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

#The DataFrame contains homogenous column data, operations can be
sensibly done both vertically and horizontally.
#The count method returns the number of non-missing values.
#By default, its axis parameter is set to 0:

In [65]:
 college_ugds_.count()

UGDS_WHITE    6874
UGDS_BLACK    6874
UGDS_HISP     6874
UGDS_ASIAN    6874
UGDS_AIAN     6874
UGDS_NHPI     6874
UGDS_2MOR     6874
UGDS_NRA      6874
UGDS_UNKN     6874
dtype: int64

In [66]:
college_ugds_.count(axis='index')

UGDS_WHITE    6874
UGDS_BLACK    6874
UGDS_HISP     6874
UGDS_ASIAN    6874
UGDS_AIAN     6874
UGDS_NHPI     6874
UGDS_2MOR     6874
UGDS_NRA      6874
UGDS_UNKN     6874
dtype: int64

Changing the axis parameter to 1/columns transposes the operation so that each
row of data has a count of its non-missing values:

In [67]:
college_ugds_.count(axis='columns').head()

INSTNM
Alabama A & M University               9
University of Alabama at Birmingham    9
Amridge University                     9
University of Alabama in Huntsville    9
Alabama State University               9
dtype: int64

#Instead of counting non-missing values,
we can sum all the values in each row.
#Each row of percentages should add up to 1.

In [68]:
college_ugds_.sum(axis='columns').head()

INSTNM
Alabama A & M University               1.0000
University of Alabama at Birmingham    0.9999
Amridge University                     1.0000
University of Alabama in Huntsville    1.0000
Alabama State University               1.0000
dtype: float64

#To get an idea of the distribution of each column, the median method can be
used:

In [69]:
 college_ugds_.median(axis='index')

UGDS_WHITE    0.55570
UGDS_BLACK    0.10005
UGDS_HISP     0.07140
UGDS_ASIAN    0.01290
UGDS_AIAN     0.00260
UGDS_NHPI     0.00000
UGDS_2MOR     0.01750
UGDS_NRA      0.00000
UGDS_UNKN     0.01430
dtype: float64

#The "cumsum" method with axis=1 accumulates the race percentages across each row. It
gives a slightly different view of the data. 
#For example, it is very easy to see the exact
percentage of white, black, and Hispanic together for each school:

In [70]:
college_ugds_cumsum = college_ugds_.cumsum(axis=1)
college_ugds_cumsum.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9686,0.9741,0.9760,0.9784,0.9803,0.9803,0.9862,1.0000
University of Alabama at Birmingham,0.5922,0.8522,0.8805,0.9323,0.9345,0.9352,0.9720,0.9899,0.9999
Amridge University,0.2990,0.7182,0.7251,0.7285,0.7285,0.7285,0.7285,0.7285,1.0000
University of Alabama in Huntsville,0.6988,0.8243,0.8625,0.9001,0.9144,0.9146,0.9318,0.9650,1.0000
Alabama State University,0.0158,0.9366,0.9487,0.9506,0.9516,0.9522,0.9620,0.9863,1.0000

In [71]:
 pd.read_csv('data/college_diversity.csv', index_col='School')

                                                   Diversity Index
School
Rutgers University--Newark  Newark, NJ                        0.76
Andrews University  Berrien Springs, MI                       0.74
Stanford University  Stanford, CA                             0.74
University of Houston  Houston, TX                            0.74
University of Nevada--Las Vegas  Las Vegas, NV                0.74
University of San Francisco  San Francisco, CA                0.74
San Francisco State University  San Francisco, CA             0.73
University of Illinois--Chicago  Chicago, IL                  0.73
New Jersey Institute of Technology  Newark, NJ                0.72
Texas Woman's University  Denton, TX                          0.72

In [72]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')
college_ugds_ = college.filter(like='UGDS_')

Many of these colleges have missing values for all their race columns.
#We can
count all the missing values for each row and sort the resulting Series from the
highest to lowest. 
#This will reveal the colleges that have missing values:

In [73]:
college_ugds_.isnull().sum(axis=1).sort_values(ascending=False).head()

INSTNM
Excel Learning Center-San Antonio South         9
Philadelphia College of Osteopathic Medicine    9
Assemblies of God Theological Seminary          9
Episcopal Divinity School                       9
Phillips Graduate Institute                     9
dtype: int64

#we
can use the dropna method to drop all rows that have all nine race percentages
missing.
#We can then count the remaining missing values:

In [74]:
college_ugds_ = college_ugds_.dropna(how='all')
college_ugds_.isnull().sum()

UGDS_WHITE    0
UGDS_BLACK    0
UGDS_HISP     0
UGDS_ASIAN    0
UGDS_AIAN     0
UGDS_NHPI     0
UGDS_2MOR     0
UGDS_NRA      0
UGDS_UNKN     0
dtype: int64

#There are no missing values left in the dataset. We can now calculate our
diversity metric. 
#To get started, we will use the greater than or equal DataFrame
method, "ge" to convert each value to a boolean:

In [75]:
 college_ugds_.ge(.15)

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,False,True,False,False,False,False,False,False,False
University of Alabama at Birmingham,True,True,False,False,False,False,False,False,False
Amridge University,True,True,False,False,False,False,False,False,True
University of Alabama in Huntsville,True,False,False,False,False,False,False,False,False
Alabama State University,False,True,False,False,False,False,False,False,False
The University of Alabama,True,False,False,False,False,False,False,False,False
Central Alabama Community College,True,True,False,False,False,False,False,False,False
Athens State University,True,False,False,False,False,False,False,False,False
Auburn University at Montgomery,True,True,False,False,False,False,False,False,False
Auburn University,True,False,False,False,False,False,False,False,False
Birmingham Southern College,True,False,False,False,False,False,False,False,False
Chattahoochee Valley Community College,True,True,False,False,False,False,False,False,False
Concordia College Alabama,False,True,False,False,False,False,False,False,False
South University-Montgomery,True,True,False,False,False,False,False,False,False
Enterprise State Community College,True,True,False,False,False,False,False,False,False
James H Faulkner State Community College,True,True,False,False,False,False,False,False,False
Faulkner University,True,True,False,False,False,False,False,False,False
Gadsden State Community College,True,True,False,False,False,False,False,False,False
New Beginning College of Cosmetology,True,False,False,False,False,False,False,False,False
George C Wallace State Community College-Dothan,True,True,False,False,False,False,False,False,False
George C Wallace State Community College-Hanceville,True,False,False,False,False,False,False,False,False
George C Wallace State Community College-Selma,True,True,False,False,False,False,False,False,False
Herzing University-Birmingham,True,True,False,False,False,False,False,False,False
Huntingdon College,True,True,False,False,False,False,False,False,False
Heritage Christian University,True,False,False,False,False,False,False,False,False
J F Drake State Community and Technical College,True,True,False,False,False,False,False,False,False
Jacksonville State University,True,True,False,False,False,False,False,False,False
Jefferson Davis Community College,True,True,False,False,False,False,False,False,False
Jefferson State Community College,True,True,False,False,False,False,False,False,False
John C Calhoun State Community College,True,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
Tint School of Makeup & Cosmetology-Seattle,True,False,True,False,False,False,False,False,False
Centro de Estudios Multidisciplinarios-Mayaguez,False,False,True,False,False,False,False,False,False
Heritage College-Cleveland,True,True,False,False,False,False,False,False,False
Aveda Institute-Phoenix,True,False,True,False,False,False,False,False,False
University of North Texas at Dallas,False,True,True,False,False,False,False,False,False
BridgeValley Community & Technical College,True,False,False,False,False,False,False,False,False
Northwest College-Medford,True,False,True,False,False,False,False,False,False
Virginia College-Fort Pierce,True,True,False,False,False,False,False,False,False
Houston Training Schools-Gessner,False,False,True,False,False,False,False,False,False
Empire Beauty School-Buffalo,True,True,False,False,False,False,False,False,False
Paul Mitchell the School-Toledo,True,True,False,False,False,True,False,False,False
MJ's Barber Academy,False,True,False,False,False,False,False,False,False
Trine University-Arizona Regional Campus,True,False,True,False,False,False,False,False,False
Regency Beauty Institute-Gaithersburg,True,True,True,False,False,False,True,False,False
Georgia Military College,True,True,False,False,False,False,False,False,False
New Horizons Medical Institute-Winder,True,True,False,False,False,False,False,False,False
SAE Institute of Technology-Chicago,True,True,True,False,False,False,False,False,False
Beau Monde College of Hair Design-Beau Monde Academy of Cosmetology,True,False,True,False,False,False,False,False,False
Fayette Beauty Academy-Ritz Beauty Academy,False,True,False,False,False,False,False,False,False
Fountain of Youth Academy of Cosmetology,True,False,False,False,False,False,False,False,False
MCI Institute of Technology-Boca Raton,False,True,True,False,False,False,False,False,False
West Coast University-Miami,True,True,True,False,False,False,False,False,False
National American University-Houston,True,True,False,False,False,False,False,False,False
Aparicio-Levy Technical College,True,False,True,False,False,False,False,False,False
Fred D. Learey Technical College,True,False,True,False,False,False,False,False,True
Hollywood Institute of Beauty Careers-West Palm Beach,True,True,True,False,False,False,False,False,False
Hollywood Institute of Beauty Careers-Casselberry,False,True,True,False,False,False,False,False,False
Coachella Valley Beauty College-Beaumont,True,False,True,False,False,False,False,False,False
Dewey University-Mayaguez,False,False,True,False,False,False,False,False,False
Coastal Pines Technical College,True,True,False,False,False,False,False,False,False

#we can use the sum method to count the True values for each college.
Notice that a Series is returned:

In [76]:
diversity_metric = college_ugds_.ge(.15).sum(axis='columns')
diversity_metric.head()

INSTNM
Alabama A & M University               1
University of Alabama at Birmingham    2
Amridge University                     3
University of Alabama in Huntsville    1
Alabama State University               1
dtype: int64

#To get an idea of the distribution, let's use the "value_counts" method on this
Series:

In [77]:
 diversity_metric.value_counts()

1    3042
2    2884
3     876
4      63
0       7
5       2
dtype: int64

#Two schools have more than 15% in five different race categories.
#Let's sort the diversity_metric Series to find out which ones they are:

In [78]:
diversity_metric.sort_values(ascending=False).head()

INSTNM
Regency Beauty Institute-Austin          5
Central Texas Beauty College-Temple      5
Sullivan and Cogliano Training Center    4
Ambria College of Nursing                4
Berkeley College-New York                4
dtype: int64

#It seems a little suspicious that schools can be that diverse. 
#Let's look at the raw
percentages from these top two schools. 
#The .loc indexer is used to specifically
select based on the index label:

In [79]:
 college_ugds_.loc[['Regency Beauty Institute-Austin','Central Texas Beauty College-Temple']]

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Regency Beauty Institute-Austin,0.1867,0.2133,0.1600,0.0000,0.0,0.0,0.1733,0.0,0.2667
Central Texas Beauty College-Temple,0.1616,0.2323,0.2626,0.0202,0.0,0.0,0.1717,0.0,0.1515

#It appears that several categories were aggregated into the unknown and two or
more races column. 
#Regardless of this, they both appear to be quite diverse. 
#We
can see how the top 10 US News schools fared with this basic diversity metric:

In [80]:
us_news_top = ['Rutgers University-Newark',
                'Andrews University',
                'Stanford University',
                'University of Houston',
                'University of Nevada-Las Vegas']

In [81]:
diversity_metric.loc[us_news_top]

INSTNM
Rutgers University-Newark         4
Andrews University                3
Stanford University               3
University of Houston             3
University of Nevada-Las Vegas    3
dtype: int64

#We can find the schools that are least diverse by ordering them by their
maximum race percentage:

In [82]:
 college_ugds_.max(axis=1).sort_values(ascending=False).head(10)

INSTNM
Dewey University-Manati                               1.0
Yeshiva and Kollel Harbotzas Torah                    1.0
Mr Leon's School of Hair Design-Lewiston              1.0
Dewey University-Bayamon                              1.0
Shepherds Theological Seminary                        1.0
Yeshiva Gedolah Kesser Torah                          1.0
Monteclaro Escuela de Hoteleria y Artes Culinarias    1.0
Yeshiva Shaar Hatorah                                 1.0
Bais Medrash Elyon                                    1.0
Yeshiva of Nitra Rabbinical College                   1.0
dtype: float64

#We can also determine if any school has all nine race categories exceeding 1%

In [83]:
(college_ugds_ > .01).all(axis=1).any()

True