Q.1.Demonstrate with example, how you can select (a)one column (b)two columns of DF.

In [1]:
import pandas as pd 
movie = pd.read_csv('../data/movie.csv')
movie.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinner,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [2]:
movie.shape

(4916, 28)

In [3]:
#(a)
director = movie[['director_name']]
director.head()

       director_name
0      James Cameron
1     Gore Verbinski
2         Sam Mendes
3  Christopher Nolan
4        Doug Walker

In [4]:
#(b)
director = movie[['director_name','duration']]
director.head()

       director_name  duration
0      James Cameron     178.0
1     Gore Verbinski     169.0
2         Sam Mendes     148.0
3  Christopher Nolan     164.0
4        Doug Walker       NaN

Q.2.What will happen when you pass (a) a string (b) a list into the indexing operatorof DF

#(a)
When we pass the string into the indexing operator of DF,
then print the same column which is passes into indexing operator.
Types of DataFrame is series

In [5]:
#eg.
director = movie['director_name']
type(director)

pandas.core.series.Series

#(b)
When we pass the list into the indexing operator of DF,
then print the same columns which is passes into indexing operator.
Types of DataFrame is DataFrame

In [6]:
#eg.
director = movie[['director_name','duration']]
type(director)

pandas.core.frame.DataFrame

Q.3.Select a single column from a DF in such a way that the result is also a DF.

In [7]:
director = movie[['director_name']]
director.head()

       director_name
0      James Cameron
1     Gore Verbinski
2         Sam Mendes
3  Christopher Nolan
4        Doug Walker

In [8]:
type(director)

pandas.core.frame.DataFrame

Q.4.Give two common reasons for KeyError in a DF.

We pass the string into the indexing operator of DF and this string is not present the DF,
then we have KeyError

Q.5.Explain how you can select columns of a DF using (a) Indexing operator (b) select_dtype()
and filter() methods.

In [9]:
#(a)
director = movie[['director_name','duration']]
director.head()

       director_name  duration
0      James Cameron     178.0
1     Gore Verbinski     169.0
2         Sam Mendes     148.0
3  Christopher Nolan     164.0
4        Doug Walker       NaN

In [10]:
#(b)
import pandas as pd
movie = pd.read_csv('../data/movie.csv')
movie.get_dtype_counts()

float64    13
int64       3
object     12
dtype: int64

 This method
is flexible and searches column names based on which
parameter is used. Here, we use the like parameter to search for all column
names that contain the exact string, facebook:

In [11]:
#(c)
movie.filter(like = 'facebook').head()

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
0,0.0,855.0,1000.0,4834,936.0,33000
1,563.0,1000.0,40000.0,48350,5000.0,0
2,0.0,161.0,11000.0,11700,393.0,85000
3,22000.0,23000.0,27000.0,106759,23000.0,164000
4,131.0,NaN,131.0,143,12.0,0

Q.6.Output the number of columns with each specific data type in a DF.

In [12]:
movie.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

Q.7.Explain one main difference between select_dtypes() and filter methods.

Ans.The 'select_dtypes' method takes a list of data types in its include parameterand return a DataFrame with columns is just those given data types.
This list values may be either the string name of data type or the actual Python object.

(select_dtype method to select only integer columns )

filter method is flexible and searches columns names based on which parameter to used.

Q.8. Explain the difference among like parameter and regex parameter and items
parameter used in filter method in a DF.

Ans.like parameter to search for all column names that contain the exact string.

In [13]:
movie.filter(like = 'facebook').head()

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
0,0.0,855.0,1000.0,4834,936.0,33000
1,563.0,1000.0,40000.0,48350,5000.0,0
2,0.0,161.0,11000.0,11700,393.0,85000
3,22000.0,23000.0,27000.0,106759,23000.0,164000
4,131.0,NaN,131.0,143,12.0,0

regex parameter to search for all column that have a digit somewhere in their name:

In [14]:
movie.filter(regex = '\d').head()

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
0,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
1,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
2,161.0,Rory Kinner,11000.0,Christoph Waltz,Stephanie Sigman,393.0
3,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
4,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0

items parameter to search a list of exact column names

In [15]:
movie.filter(items = ['actor_1_name','asdf']).head()

      actor_1_name
0      CCH Pounder
1      Johnny Depp
2  Christoph Waltz
3        Tom Hardy
4      Doug Walker

Q.9. Search for all the columns that have a special character somewhere in their name.

Q.10. What will happen if you provide a non-existing column name in the indexing operator of a DF?

Ans. If we provide a non-existing column name in the indexing operator of a DF, It gives Keyerror.

Q.11.What will happen if you provide a non-existing column name in the list parameter of filter
method in a DF?

Ans.

In [16]:
movie.filter(like = 'parameter').head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

Q.12.Display rows with any NaN value.

Q.13.Do you think it is useful to arrange the column names sensibly? List the guidelines to arrange
the columns.

Ans.Yes,Because its far easier to find and interpret information when columnorder is given consideration.

Guidlines to order columns

#Classify each column as either discrete or continuous.

#Group common columns within the discrete and continuous columns.

#Place the most impotant groups of columns first with categorical columns before continuous ones.

Q.14.Write the difference between discrete and continuous variables in DF.

Q.15. What is Primary Key and Foreign Key in Relational Database.

Ans.Primary Key - A column or group of columns in a table which helps us to uniquely identifies every row in that table is called a primary key.

 This DBMS can't be a duplicate. The same value can't appear more than once in the table.

Foreign Key - A foreign key is a column which is added to create a relationship with another table.

Foreign keys help us to maintain data integrity and also allows navigation between two different instances of an entity.

Every relationship in the model needs to be supported by a foreign key.

Q.16.. While ordering (arranging) the column name, where will you place the Primary Key and the
Foreign Key of the data ?

Do all the datasets have Primary and Foreign Keys ?

Q.17 List the basic descriptive attributes and their functions with examples.

Ans.Basic Descriptive attributes : shape,size and ndim

In [17]:
movie = pd.read_csv('../data/movie.csv',index_col = 'director_name')
movie

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
director_name,,,,,,,,,,,,,,,,,,,,,
James Cameron,Color,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Gore Verbinski,Color,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Sam Mendes,Color,602.0,148.0,0.0,161.0,Rory Kinner,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
Christopher Nolan,Color,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Doug Walker,NaN,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
Andrew Stanton,Color,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
Sam Raimi,Color,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,J.K. Simmons,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
Nathan Greno,Color,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
Joss Whedon,Color,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,Chris Hemsworth,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
David Yates,Color,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
Zack Snyder,Color,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,Henry Cavill,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
Bryan Singer,Color,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,Kevin Spacey,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
Marc Forster,Color,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,Giancarlo Giannini,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
Gore Verbinski,Color,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,Johnny Depp,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
Gore Verbinski,Color,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,Johnny Depp,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
Zack Snyder,Color,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
Andrew Adamson,Color,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,Peter Dinklage,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
Joss Whedon,Color,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
Rob Marshall,Color,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,Johnny Depp,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
Barry Sonnenfeld,Color,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,Will Smith,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
Peter Jackson,Color,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,Aidan Turner,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
Marc Webb,Color,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,Emma Stone,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
Ridley Scott,Color,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,Mark Addy,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
Peter Jackson,Color,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,Aidan Turner,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
Chris Weitz,Color,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,Christopher Lee,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
Peter Jackson,Color,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,Naomi Watts,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
James Cameron,Color,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,Leonardo DiCaprio,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
Anthony Russo,Color,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,Robert Downey Jr.,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
Peter Berg,Color,377.0,131.0,532.0,627.0,Alexander SkarsgÃ¥rd,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
Colin Trevorrow,Color,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Eric Eason,Color,28.0,79.0,3.0,42.0,Panchito GÃ³mez,93.0,NaN,Drama|Family,Franky G,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
Uwe Boll,Color,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,Matt Frewer,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
Richard Linklater,Black and White,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,Tommy Pallotta,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
Joseph Mazzella,Color,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,Tjasa Ferme,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
Travis Legge,Color,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,Kristen Seavey,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
Alex Kendrick,Color,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,Shannen Fields,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
Marcus Nispel,Color,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,Ashley Tramonte,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
Brandon Landers,NaN,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,Robbie Barnes,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
Jay Duplass,Color,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,Mark Duplass,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
Jim Chuchu,Black and White,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,Paul Ogola,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
Daryl Wein,Color,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,Zoe Lister-Jones,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
Jason Trost,Color,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,Sean Whalen,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
John Waters,Color,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,Divine,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
Olivier Assayas,Color,81.0,110.0,107.0,45.0,BÃ©atrice Dalle,576.0,136007.0,Drama|Music|Romance,Maggie Cheung,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
Jafar Panahi,Color,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,Fereshteh Sadre Orafaiy,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
Ivan Kavanagh,Black and White,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,Patrick O'Donnell,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
Kiyoshi Kurosawa,Color,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,KÃ´ji Yakusho,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
Tadeo Garcia,Color,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,Tatiana Suarez-Pico,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
Thomas L. Phillips,Color,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,Julianna Pitt,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
Ash Baron-Cohen,Color,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,Peter Greene,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
Shane Carruth,Color,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
Neill Dela Llana,Color,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,Ian Gamazon,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
Robert Rodriguez,Color,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
Anthony Vallone,Color,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,Richard Jewell,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
Edward Burns,Color,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,Kerry BishÃ©,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
Scott Smith,Color,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
NaN,Color,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
Benjamin Roberds,Color,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Daniel Hsia,Color,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
Jon Gunn,Color,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [18]:
movie.shape

(4916, 27)

In [19]:
movie.size

132732

In [20]:
movie.ndim

2

    Basic descriptive function : len()

In [21]:
len(movie)

4916

Q.18. Demonstrate the function of len() method.

Ans. len function to return the number of rows.

19. How can you find the number of non-missing values for each column of a DF ?

Ans.count() method to find the number of non-missing values for each column of a DF.

Q.20.List all the methods that compute statistics. Demonstrate their use with examples.

Ans.Following the method of that compute statistics.

(a): mean()

(b):std()

(c):min()

(d):max()

(e):percentiles()

Examples:

In [24]:
#(a):
movie.mean()

num_critic_for_reviews       1.379889e+02
duration                     1.070908e+02
director_facebook_likes      6.910145e+02
actor_3_facebook_likes       6.312763e+02
actor_1_facebook_likes       6.494488e+03
gross                        4.764451e+07
num_voted_users              8.264492e+04
cast_total_facebook_likes    9.579816e+03
facenumber_in_poster         1.377320e+00
num_user_for_reviews         2.676688e+02
budget                       3.654749e+07
title_year                   2.002448e+03
actor_2_facebook_likes       1.621924e+03
imdb_score                   6.437429e+00
aspect_ratio                 2.222349e+00
movie_facebook_likes         7.348294e+03
dtype: float64

In [25]:
#(b)
movie.std()

num_critic_for_reviews       1.202394e+02
duration                     2.528602e+01
director_facebook_likes      2.832954e+03
actor_3_facebook_likes       1.625875e+03
actor_1_facebook_likes       1.510699e+04
gross                        6.737255e+07
num_voted_users              1.383222e+05
cast_total_facebook_likes    1.816432e+04
facenumber_in_poster         2.023826e+00
num_user_for_reviews         3.729348e+02
budget                       1.002427e+08
title_year                   1.245398e+01
actor_2_facebook_likes       4.011300e+03
imdb_score                   1.127802e+00
aspect_ratio                 1.402940e+00
movie_facebook_likes         1.920602e+04
dtype: float64

In [26]:
#(c):
movie.min()

num_critic_for_reviews          1.00
duration                        7.00
director_facebook_likes         0.00
actor_3_facebook_likes          0.00
actor_1_facebook_likes          0.00
gross                         162.00
num_voted_users                 5.00
cast_total_facebook_likes       0.00
facenumber_in_poster            0.00
num_user_for_reviews            1.00
budget                        218.00
title_year                   1916.00
actor_2_facebook_likes          0.00
imdb_score                      1.60
aspect_ratio                    1.18
movie_facebook_likes            0.00
dtype: float64

In [27]:
#(d):
movie.max()

num_critic_for_reviews       8.130000e+02
duration                     5.110000e+02
director_facebook_likes      2.300000e+04
actor_3_facebook_likes       2.300000e+04
actor_1_facebook_likes       6.400000e+05
gross                        7.605058e+08
num_voted_users              1.689764e+06
cast_total_facebook_likes    6.567300e+05
facenumber_in_poster         4.300000e+01
num_user_for_reviews         5.060000e+03
budget                       4.200000e+09
title_year                   2.016000e+03
actor_2_facebook_likes       1.370000e+05
imdb_score                   9.500000e+00
aspect_ratio                 1.600000e+01
movie_facebook_likes         3.490000e+05
dtype: float64

In [31]:
#(e):
movie.describe(percentiles=[.01,.3,.99])

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
1%,2.000000,43.000000,0.000000,0.000000,6.080000,8.474800e+03,5.300000e+01,6.000000,0.000000,1.940000,6.000000e+04,1951.000000,0.000000,3.100000,1.330000,0.000000
30%,60.000000,95.000000,11.000000,176.000000,694.000000,7.914069e+06,1.186450e+04,1684.500000,0.000000,80.000000,8.000000e+06,2000.000000,345.000000,6.000000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000
99%,546.680000,189.000000,16000.000000,11000.000000,44920.000000,3.264128e+08,6.815846e+05,62413.900000,8.000000,1999.240000,2.000000e+08,2016.000000,17000.000000,8.500000,4.000000,93850.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [34]:
movie.quantile(.25)

num_critic_for_reviews            49.00
duration                          93.00
director_facebook_likes            7.00
actor_3_facebook_likes           132.00
actor_1_facebook_likes           607.00
gross                        5019656.25
num_voted_users                 8361.75
cast_total_facebook_likes       1394.75
facenumber_in_poster               0.00
num_user_for_reviews              64.00
budget                       6000000.00
title_year                      1999.00
actor_2_facebook_likes           277.00
imdb_score                         5.80
aspect_ratio                       1.85
movie_facebook_likes               0.00
Name: 0.25, dtype: float64

In [35]:
movie.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,49.000000,93.000000,7.000000,132.000000,607.000000,5.019656e+06,8.361750e+03,1394.750000,0.000000,64.000000,6.000000e+06,1999.000000,277.000000,5.800000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000
75%,191.000000,118.000000,189.750000,633.000000,11000.000000,6.110841e+07,9.377275e+04,13616.750000,2.000000,320.500000,4.300000e+07,2011.000000,912.000000,7.200000,2.350000,2000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

21.How does Pandas deal with the missing values while computing statistics?

In [38]:
movie.min(skipna=False)

num_critic_for_reviews       NaN
duration                     NaN
director_facebook_likes      NaN
actor_3_facebook_likes       NaN
actor_1_facebook_likes       NaN
gross                        NaN
num_voted_users              5.0
cast_total_facebook_likes    0.0
facenumber_in_poster         NaN
num_user_for_reviews         NaN
budget                       NaN
title_year                   NaN
actor_2_facebook_likes       NaN
imdb_score                   1.6
aspect_ratio                 NaN
movie_facebook_likes         0.0
dtype: float64